### ISSUE TITLE
Update contacts in the newsroom page

### ISSUE THREAD

**Issue by jayasanka-sack** [LSFLK/MedicinesforLK#110]
**Is your feature request related to a problem? Please describe.**
Add following contact to the newsroom page. 

Zafran Packeerally 
070 378 8685 
email: [zafran.packeerally@redcross.lk](mailto:zafran.packeerally@redcross.lk)
 
Also "Naveendra SENARATHNE" should be "Naveendra Senarathne"

**Comment by Bawanthathilan** [comment]
May I work on this

**Comment by jayasanka-sack** [comment]
Sure. Go ahead!
