### ISSUE TITLE
Make the aid packages appear uncollapsed 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#112]
Make the created aid packages appear uncollapsed. Allow the user to collapse each need section. Otherwise if you have e.g. 30 needs, it is hard to navigate them in the create aid packages section when they are all collapsed. 

![Screen Shot 2022-07-11 at 12 57 46](https://user-images.githubusercontent.com/44461004/178245929-e2b18bd5-79b3-4a24-8ff4-7ae49454ed02.jpg)

**Comment by jayasanka-sack** [comment]
working on it
