### ISSUE TITLE
Units are empty for some medical needs.

### ISSUE THREAD

**Issue by jayasanka-sack** [LSFLK/MedicinesforLK#113]
**Is your feature request related to a problem? Please describe.**
units of some medical Items are empty. (GET /medicalneeds)

This is the file I uploaded:
[Needs_Upload_success.csv](https://github.com/LSFLK/MedicinesforLK/files/9083280/Needs_Upload_success.csv)

**Comment by anupama-pathirage** [comment]
The reason is units are missing in the master data provided by @akbandara on the medical items. 
@akbandara Any update on this?

**Comment by anupama-pathirage** [comment]
Master items with the patched unit details are added to DB. Also above mentioned requirements for uploads were done already.

**Comment by akbandara** [comment]
Tested - confirm that upload of Needs and Supplier Quotation CSVs is working seamlessly
