### ISSUE TITLE
Need id is displayed instead of item name

### ISSUE THREAD

**Issue by anupama-pathirage** [LSFLK/MedicinesforLK#129]
$subject. check the below UI. 

In the previous step, need name is given as item name. So here also it should be item name.

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/16300038/178349605-b0210d1c-9c0c-481c-87bf-56a49c2511ac.png">

**Comment by jayasanka-sack** [comment]
@nipuna777 Could you please look into this?

**Comment by nipuna777** [comment]
@jayasanka-sack Yup, we don't do the calculations yet. I'll fix this.
