### ISSUE TITLE
Aid package details goes to pledge status instead of details page

### ISSUE THREAD

**Issue by anupama-pathirage** [LSFLK/MedicinesforLK#130]
$subect and to get the correct page , need to access via breadcrumbs. 

https://user-images.githubusercontent.com/16300038/178358945-580dd1a2-13d6-4f1d-81ce-f367170c1fde.mov

**Comment by jayasanka-sack** [comment]
Yeah wiring of buttons is inverted (pledge details and aid package details go to opposite page)

**Comment by anjula-sack** [comment]
Hello @anupama-pathirage @jayasanka-sack, I would like to work on this.

**Comment by jayasanka-sack** [comment]
Sure!
