### ISSUE TITLE
Thousand separators for quantity figures 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#132]
- [ ] Thousand separators for figures to make it easier for admin users to work with medicine quantities
![Screen Shot 2022-07-12 at 09 57 19](https://user-images.githubusercontent.com/44461004/178408672-abca0ce3-1c58-4cfa-96fd-0983ca91e13f.jpg)

**Comment by jayasanka-sack** [comment]
Also, better if we could make the numbers right-aligned.

**Comment by nshamit** [comment]
Fields:

- [ ] Quantity remaining 
- [ ] Remaining need 
- [ ] Max
