### ISSUE TITLE
Changing the signInRedirectURL in the config doesn't work

### ISSUE THREAD

**Issue by anjula-sack** [LSFLK/MedicinesforLK#139]
**Is your feature request related to a problem? Please describe.**
When developing locally signing redirection needs to change to `http://localhost:3000` but changing the signInRedirectURL gives an error.
<img width="558" alt="Screenshot 2022-07-12 at 1 09 05 PM" src="https://user-images.githubusercontent.com/43912578/178438802-991b9293-9fa7-4534-8336-8f158cd8857c.png">

**Describe the solution you'd like**
- A solution is required to handle sign in redirection

**Comment by jayasanka-sack** [comment]
@NipunaMarcus Could you please look into this?

**Comment by jayasanka-sack** [comment]
@anjula-sack Could you please try `https`?

**Comment by anjula-sack** [comment]
> @anjula-sack Could you please try `https`?

I'm getting this. 
<img width="1680" alt="Screenshot 2022-07-12 at 2 08 51 PM" src="https://user-images.githubusercontent.com/43912578/178448175-2a742771-0b63-48fd-8e88-6aed273ca3f8.png">

**Comment by jayasanka-sack** [comment]
@NipunaMarcus I think we should configure it from the Asgardeo side.

**Comment by jayasanka-sack** [comment]
@anjula-sack Could you please check `http`?  Nipuna whitelisted it.

**Comment by anjula-sack** [comment]
> @anjula-sack Could you please check `http`? Nipuna whitelisted it.

still same

**Comment by anjula-sack** [comment]
getting this as well
<img width="711" alt="Screenshot 2022-07-12 at 2 38 49 PM" src="https://user-images.githubusercontent.com/43912578/178454335-6fa939c9-5925-49e2-bfbf-2966bd8eb71a.png">

**Comment by anjula-sack** [comment]
It does work with `http`. I was changing the config previously.

**Comment by jayasanka-sack** [comment]
For me, changing the  signInRedirectURL to `http://localhost:3000` causes an infinite redirection loop

**Comment by jayasanka-sack** [comment]
This has been fixed. Closing the issue.
