### ISSUE TITLE
Donor checks the status of the closed aid package (order placed, order shipped, order received). 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#155]
- [ ] Donor checks the status of the closed aid package (order placed, order shipped, order received). 

![Screen Shot 2022-07-12 at 19 01 44](https://user-images.githubusercontent.com/44461004/178503047-e117cbb0-932b-4bf7-a01c-279d1ac59550.jpg)

**Comment by jayasanka-sack** [comment]
Fixed at: https://github.com/LSFLK/MedicinesforLK/pull/164

The statuses we have on the implementation are a bit different, btw.
