### ISSUE TITLE
Create aid package - supplier detail needs to show the CIF (medicine price) value as well

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#156]
- [ ] Create aid package - supplier detail needs to show the CIF (medicine price) value as well.

**Comment by nipuna777** [comment]
@nshamit Would it be possible to get a screenshot of where we would want to see this information?

**Comment by jayasanka-sack** [comment]
It should be displayed here: 

Also, we should display the unit price, as well. 
<img width="1346" alt="Screenshot 2022-07-12 at 22 14 35" src="https://user-images.githubusercontent.com/33048395/178547671-6ecb45e9-80d1-4985-aa5c-97948de9491c.png">
