### ISSUE TITLE
Edit pledge page is not working

### ISSUE THREAD

**Issue by jayasanka-sack** [LSFLK/MedicinesforLK#160]
**Is your feature request related to a problem? Please describe.**
The edit pledge page is not working. 

1. Click on an edit button of a donor here:
https://admin-portal-rouge.vercel.app/packages/6/pledge-status

**Comment by anjula-sack** [comment]
I would like to work on this @jayasanka-sack

**Comment by YaiyaSam** [comment]
oh wait 😶

**Comment by YaiyaSam** [comment]
> I would like to work on this @jayasanka-sack

sorryyyy i just sent the pr cuz i didnt see it was assigned to anyone

**Comment by anjula-sack** [comment]
> > I would like to work on this @jayasanka-sack
> 
> sorryyyy i just sent the pr cuz i didnt see it was assigned to anyone

no worries
