### ISSUE TITLE
If aid package goal is reached in full, you cannot update (edit) your pledge and other related issues 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#185]
- [x] If aid package goal is reached in FULL, you cannot update (edit) your pledge. 
- [x] If an aid package goal is reached in PART, you CAN edit your pledge. 
- [ ] Editing a pledge with 0 should be allowed (to remove a previous pledge amount)

**Comment by jayasanka-sack** [comment]
@Gravewalker666 This is already fixed, right?

**Comment by Gravewalker666** [comment]
Ah yeah, this is fixed except for the 3rd point I think. 
Can somebody else please work on that? I'm a bit busy with some academics.

**Comment by jayasanka-sack** [comment]
It's alright, @Gravewalker666!

@nshamit What if we can add a remove button, instead? 

@YujithIsura Can you look into this?

**Comment by anjula-sack** [comment]
@Gravewalker666 @jayasanka-sack I would like to work on this.

**Comment by jayasanka-sack** [comment]
Thanks, Please go ahead @anjula-sack !
