### ISSUE TITLE
Less technical error message is required for supplier quotation upload

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#187]
- [ ] Less technical error message is required for supplier quotation upload

![Uploading Screen Shot 2022-07-14 at 20.27.09.jpg…]()

**Comment by nshamit** [comment]
![Screen Shot 2022-07-14 at 20 27 09](https://user-images.githubusercontent.com/44461004/179020950-37dd19c9-f4a4-4f9c-906e-6a29574a7df9.jpg)

@anupama-pathirage updated, sorry for missing it.

**Comment by anupama-pathirage** [comment]
Thanks,

Can you please suggest a sample error message for this? I added `Check line 1` to make it non technical, but without exactly telling which value is causing the issue (i.e. `Amount Available` in this case) it will be hard for the user to find the issue in the file.

**Comment by anupama-pathirage** [comment]
Closing this as we are not getting this kind of csv as per the comment in https://github.com/LSFLK/MedicinesforLK/issues/113#issuecomment-1184609815
