### ISSUE TITLE
Creating an aid package and reducing the medicine quantity available from a particular supplier does not prevent the creation of another aid package with the same quantity of medicines from the same supplier. 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#189]
- [ ] Creating an aid package and reducing the medicine quantity available from a particular supplier does not prevent the creation of another aid package with the same quantity of medicines from the same supplier. 

When an aid package is created utilizing 430/435 units of a medicine, when I create  a second aid package with the same medicine, I can still allocate 430 units out of 435 instead of allocating only 5 units. 

The max quantity does not change dynamically so if there is an aid package already created, I have to guess/trial and error how many units were assigned to the previous aid packages and what the new max quantity is for the new aid package.  The new max number should be automatically reflected on creation of an aid package.

**Comment by AmilaJ** [comment]
Restriction added to prevent the exceeding amounts on the aid package more than the medical need.
