### ISSUE TITLE
Currently, you can edit the quantity of medicines in an aid package for a published aid package. 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#191]
- [x] You can edit the quantity of medicines in an aid package for a published aid package.

**Comment by nshamit** [comment]
@YaiyaSam revision as discussed 

- [ ] We should be able to register the initial amount we need to raise for an aid package. 
- [ ] We should still be able to edit the quantities of medicine in the aid package to close the aid package, and see 1) the revised medicines quantities and 2) corresponding $ value to the aid package in addition to the initial 1) medicines quantities and 2) corresponding $ value to the aid package. Can we achieve this through some auto population of a comment in the comment box through a workflow e.g.

- Press edit button
- Message asking if you want to change the medicine quantities> click yes
- Auto population of comment with initial medicine quantities and total $ value of aid package. 
- Saving the new quantities and $ value of aid package in the table. 

What do you think?

**Comment by nshamit** [comment]
What is left to be done:

We require the period information (1/7/2022) of the medicine to be included in 1) The list of aid packages and 2) the detailed aid package view. 

This is because when we’re looking at the aid package list or the detailed aid package view, the user cannot prioritize 1/7/2022 aid packages over other periods for editing / closure. 

![Screen Shot 2022-07-22 at 17 50 00](https://user-images.githubusercontent.com/44461004/180438303-5241c11f-9e82-49c7-8f8d-e9f883758fe3.jpg)
![Screen Shot 2022-07-22 at 17 50 08](https://user-images.githubusercontent.com/44461004/180438329-04f49b9b-4a68-47d3-9dde-d160c58a6eb0.jpg)

**Comment by nipuna777** [comment]
There are two ways an aid package could go to the 'published' state.

1. User publishes a new aid package from the aid package creation page
2. User publishes a draft aid package and then moves it into the published state. 

We can add a comment after each of these requests.
I will make that change to unblock this issue.

---

But I don't think that this is the right solution.
If we want a log of changes, we should be setting it in the backend on state changes.
