### ISSUE TITLE
Needs CSV issues / requirements 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#193]
- [ ] Needs CSV and should be downloadable and then easily uploaded, but is throwing errors.
- [ ] Needs for medical supplies needs to work without throwing errors.

**Comment by anupama-pathirage** [comment]
Closing as per the comment https://github.com/LSFLK/MedicinesforLK/issues/113#issuecomment-1186523817

**Comment by akbandara** [comment]
Confirm that this has been tested and works correctly now
