### ISSUE TITLE
Validation on donor status and aid package status 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#198]
- [ ] Should not be able to have a donor status as "pledged" and an aid package status as "shipped". 
Statuses should align this way:

1. When aid package is "published", pledge status can be "pledged"
2. When aid package is "awaiting payment", pledge status can be "payment initiated" or "payment confirmed"
3. When aid package is "ordered", "shipped", "received at MOH" or "delivered", pledge status must be "payment confirmed"

**Comment by ManojLL** [comment]
shall I work on this?

**Comment by YaiyaSam** [comment]
> shall I work on this?

sure. go ahead

**Comment by ManojLL** [comment]
@YaiyaSam What is the email and PW for login to the admin portal?

**Comment by YaiyaSam** [comment]
> @YaiyaSam What is the email and PW for login to the admin portal?
login username: nipunamarcus2@gmail.com
pw: liveSession10

**Comment by YaiyaSam** [comment]
@ManojLL also change these two lines in the config.json file

>   "signInRedirectURL": "http://localhost:3000",
  "signOutRedirectURL": "http://localhost:3000",

**Comment by jayasanka-sack** [comment]
@ManojLL @YaiyaSam 
I think this has to be handled on the backend. Not from the front end. 

In order to achieve the requirement. The pledge status should be changed when changing the status of a package. 

CC: @anupama-pathirage @AmilaJ

**Comment by jayasanka-sack** [comment]
Update: This has to be validated on the front end. 

@ManojLL Any reason for closing this PR?
https://github.com/LSFLK/MedicinesforLK/pull/243

**Comment by nshamit** [comment]
Edited: added 2nd line, term in bold. 

When aid package is "published", pledge status can be "pledged"
When aid package is "awaiting payment", pledge status can be **"pledged",**  "payment initiated" or "payment confirmed"
When aid package is "ordered", "shipped", "received at MOH" or "delivered", pledge status must be "payment confirmed"
