### ISSUE TITLE
When editing aid package medicine quantities, need to be able to see quantities return to remaining need quantity

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#205]
- [x] When editing aid package medicine quantities, need to be able to see quantities return to remaining need quantity
- [x] Should be able to see the time period associated with the medicine need e.g.  7/1/2022
- [ ] When closing an aid package, should be able to edit quantities of medicine and see the quantity adjustment (adding back medicines, or increasing quantities in the aid package) corresponding to the period. 

Connected to : #190  and also #191

**Comment by nshamit** [comment]
- [ ]  Should be able to see the time period associated with the medicine need e.g. 7/1/2022
I think the above is still left to be done @YaiyaSam right?

**Comment by AmilaJ** [comment]
added period to aidpackageitem. supplier is available already inside the aidpackageitem->quotation->supplier element on response

**Comment by nshamit** [comment]
What is left to be done:

We require the period information (1/7/2022) of the medicine to be included in 1) The list of aid packages and 2) the detailed aid package view.

This is because when we’re looking at the aid package list or the detailed aid package view, the user cannot prioritize 1/7/2022 aid packages over other periods for editing / closure.

![Uploading Screen Shot 2022-07-22 at 17.50.00.jpg…]()
