### ISSUE TITLE
Quotation prices below $0.10 being stored as $0.00

### ISSUE THREAD

**Issue by akbandara** [LSFLK/MedicinesforLK#207]
If the unit price in a quotation is below $0.10 in the CSV, it is being stored as $0.00 in the system. This is affecting the following items in the CSV attached:

<google-sheets-html-origin style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

Supplier | Item Needed | Drug Registration Description | Brand Name | Period | Available Qty | Expiry Date | CIFValue
-- | -- | -- | -- | -- | -- | -- | --
Zydus | GAUZE SWABS - STERILE | India | Guaze | Aug 2022 | 20000 | 01/12/2022 | $0.01
Pan Malayan | GAUZE SWABS - STERILE | India | Guaze | Aug 2022 | 20000 | 01/12/2022 | $0.02
Pan Malayan | ABSORBENT COTTON WOOL B P / U S P/ S L S | India | Cotton Wool | Aug 2022 | 20000 | 01/12/2022 | $0.01
Pan Malayan | PARACETAMOL TABLETS BP 500MG | Malaysia | Paracetamol | Aug 2022 | 15000 | 01/11/2022 | $0.09
</google-sheets-html-origin>

[Medical Needs - SupplyQuotation-2.csv](https://github.com/LSFLK/MedicinesforLK/files/9127784/Medical.Needs.-.SupplyQuotation-2.csv)

**Comment by anupama-pathirage** [comment]
The issue is fixed, and the file is re-uploaded. so the data in the backend is rectified.

**Comment by akbandara** [comment]
Tested and confirmed that this issue is fixed.
