### ISSUE TITLE
Check status on Medical Supplies> Kalubowila for Received at MOH 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#209]
- [ ] MOH v MoH (FE)

**Comment by jayasanka-sack** [comment]
This has to be fixed on both FE and the BE. 

CC: @anupama-pathirage @AmilaJ 


@YaiyaSam please update both donor and admin portals once the backend is updated.

**Comment by anupama-pathirage** [comment]
@nshamit Can you please explain the issue further?

**Comment by nshamit** [comment]
Just tested this, I still see the issue/error. 

Follow this testing process @anupama-pathirage 

Step 1:Go into the detailed aid package, move the status from shipped to Received at MOH (capitals). 
Step 2: Go to the aid packages home page, view the status as Received at MoH  
Step 3: Go back into the detailed aid package, the status box is unchecked at Received at MOH. 


Might have something to do with the capitalization?
