### ISSUE TITLE
Should be able to delete draft and any status packages before publishing. 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#210]
- [ ] Should be able to delete draft and any status packages before publishing.

**Comment by YaiyaSam** [comment]
hey @anjula-sack  @YujithIsura would it be possible for one of u guys pick up this issue?

**Comment by anjula-sack** [comment]
I will be able to do this. can you assign me?

**Comment by jayasanka-sack** [comment]
@nshamit Could you please elaborate more on the requirement?

Is it about implementing a delete button on detailed view of an aid package?

**Comment by nshamit** [comment]
Yes, but on the inside of the details page  (Aid packages>Details (button)> takes you to the detailed view as below. 
The rationale here is that because it takes a lot of work to put together an aid package, we don't want users to accidentally delete it. By having the delete button on the aid package details page, they have to review the aid package details before they are able to delete it which ensures they are more informed at the time of deletion. 

Also - when the users click the delete button, we want a message to ask them if they are sure they want to delete the aid package. 


![Screen Shot 2022-07-21 at 09 39 40](https://user-images.githubusercontent.com/44461004/180128229-45c3f141-ac9d-4e81-a200-7bd11837e0ea.jpg)

**Comment by anjula-sack** [comment]
> 

Thanks. Got it

**Comment by nshamit** [comment]
@AmilaJ @anupama-pathirage can you help with this as Jay is unavailable today.

**Comment by udda1996** [comment]
I can start working on this.

**Comment by nshamit** [comment]
@udda1996, please do. @AmilaJ @anupama-pathirage can be consulted for help if required.
