### ISSUE TITLE
When the User clicks on "Publish" an aid package, the system should automatically move the status to "Published"

### ISSUE THREAD

**Issue by ashokvasa** [LSFLK/MedicinesforLK#212]
Currently the user has to click on publish aid package
and also come to the status workflow and click on "published"
to make the aid package appear on the public website.

**Comment by jayasanka-sack** [comment]
We are keeping packages in memory until we hit the publish button. Therefore we need a way to save a draft package.
I think we need another button named "Save draft".

**Comment by nipuna777** [comment]
@jayasanka-sack I think this is a good idea, but as things are right now, there won't be a major difference between 'published' and 'draft' packages?

Maybe we can keep only publish for now and add in 'save draft' in a future version?

**Comment by jayasanka-sack** [comment]
Draft packages won't be displayed on the public website. 

If we need to save a package without publishing, we need to save it as a draft, right?

**Comment by nipuna777** [comment]
That's a good point. I can add two buttons, the functionality would be identical apart from the status.
