### ISSUE TITLE
Create aid package>top row of each medicine in the create aid package list should list which supplier provides the medicine

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#213]
- [ ] Create aid package>top row of each medicine in the create aid package list should list which supplier provides the medicine. 

Otherwise,  the creator of aid packages has to look at each row to find the supplier info.

**Comment by nipuna777** [comment]
@nshamit Could you elaborate on how this should look like? 
Since we could have many suppliers for the same medicine, fitting them into the top row might not be possible?

**Comment by nshamit** [comment]
I'd put this after urgency, and pull the supplier names, smaller text into that top row. 
AND
I'd include some kind of sort/filter mechanism 

Those are just suggestions.
