### ISSUE TITLE
Configure airbnb eslint for the admin portal

### ISSUE THREAD

**Issue by anjula-sack** [LSFLK/MedicinesforLK#219]
**Is your feature request related to a problem? Please describe.**
- ESLint is a static code analysis tool for identifying problematic patterns found in JavaScript code. Eslint is a must-have in every project.

**Describe the solution you'd like**
- Configure eslint in the project
- Use airbnb styleguide 

This PR can be referred: https://github.com/LSFLK/MedicinesforLK/pull/201

**Comment by anjula-sack** [comment]
@jayasanka-sack can you assign me?

**Comment by jayasanka-sack** [comment]
Sure, feel free to self-assign issues :)
