### ISSUE TITLE
Dates are presented in DD/MM/YY and MM/DD/YY formats. Let's stick with DD/MM/YY

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#222]
- [ ] Dates are presented in DD/MM/YY and MM/DD/YY formats. Let's stick with DD/MM/YY

![Screen Shot 2022-07-20 at 18 08 14](https://user-images.githubusercontent.com/44461004/180124620-e73ab0d8-e7a7-4b71-8adb-adbf0e408a6c.jpg)

**Comment by anjula-sack** [comment]
I would like to work on this @nshamit

**Comment by nshamit** [comment]
Please go ahead @anjula-sack

**Comment by nshamit** [comment]
can you also include under the words "period" and "expiry date"  in light grey, (DD/MM/YY) as a guide for the users?

**Comment by anjula-sack** [comment]
> can you also include under the words "period" and "expiry date" in light grey, (DD/MM/YY) as a guide for the users?

sure
