### ISSUE TITLE
Help and Analytics is not wired 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#227]
- [ ] Help is not wired 
- [ ] Analytics is not wired

May need to wait until v3 UI designs have been shared with us from the Design team (The Last Word/Joys Chokatte).

**Comment by jayasanka-sack** [comment]
Please remove above two buttons

**Comment by muthulee** [comment]
I can work on removing buttons.

**Comment by muthulee** [comment]
Hi @jayasanka-sack ,

I am hoping to remove the below. Please confirm.

<img width="441" alt="help" src="https://user-images.githubusercontent.com/3336644/180695353-d353f0eb-ff23-4755-8b32-938bfa7676f6.png">
<img width="610" alt="analytics" src="https://user-images.githubusercontent.com/3336644/180695366-990967a1-7808-4ee8-a19d-d08baa9ed5f9.png">

Thank you,
Dimuthu

**Comment by jayasanka-sack** [comment]
Hi @muthulee, please go ahead! 😊

**Comment by muthulee** [comment]
Thank you :) ... Will do.
