### ISSUE TITLE
Add information on Choreo, Asgardeo, React with links to them and versions in the onboarding wiki

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#231]
- [ ] Can we please add more information to this on the technology stack used e.g. Choreo, Asgardeo, React with links to them and versions in the onboarding wiki (home page)

**Comment by muthulee** [comment]
@nshamit Which wiki should be updated? I can write something.

**Comment by nshamit** [comment]
https://github.com/LSFLK/MedicinesforLK/wiki

**Comment by nshamit** [comment]
@samisa-abeysinghe can we close this issue?

**Comment by samisa-abeysinghe** [comment]
Resolving as this is being address with the latest Wiki updates
