### ISSUE TITLE
Website Doctors and Suppliers page changes 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#236]
On this page: https://donor-portal-medicinesfor-lk.vercel.app/suppliers

- [x] Change the title to Doctors and Suppliers
- [ ] Add footer
- [x] Change stock image (if necessary)

![Doctors and Supplier](https://user-images.githubusercontent.com/44461004/180589783-8deaa89d-cb69-4f4d-a5d5-1b4148619ef5.jpeg)

**Comment by dinuka-rp** [comment]
@nshamit can I know where to get the stock image used in the UI here?
Would be great if I could get the link to the image itself

**Comment by nshamit** [comment]
Check the bookmark bar on the slack channel. Website v3 folder has stock photos
