### ISSUE TITLE
Website 'payment' flow 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#237]
Access this file: https://opensourcelk.slack.com/files/UDF4HA4TZ/F03QPBA2MB6/donate_flow_change_22-jul-2022.pptx  for details on the flow:

Step 1: Go from an aid package on the home page to the detailed view of an aid package in the goal pending tab
![Screen Shot 2022-07-23 at 09 38 56](https://user-images.githubusercontent.com/44461004/180589914-d1a209cb-7c36-47e1-a962-ebcf999e4eff.jpg)

Step 2: Click Donate button in the detailed aid package view 
https://donor-portal-medicinesfor-lk.vercel.app/package/9
![Screen Shot 2022-07-23 at 09 40 34](https://user-images.githubusercontent.com/44461004/180589944-d6f1e58d-943a-47cc-a899-2f4d71333dec.jpg)

Step 3: Get directed to the donors page (page is now called how to donate):
https://donor-portal-medicinesfor-lk.vercel.app/donors

![How to donate](https://user-images.githubusercontent.com/44461004/180590189-afd5226a-d222-4a64-90da-45747e6dee8e.jpeg)

Step 4: Click on Individual Donors 

Step 5: View a page which allows individual donors to pay (page not created, content not provided yet). Please create page as a minimum, call it Medicines for Sri Lanka for now

**Comment by dinuka-rp** [comment]
The pdf file link doesn't seem to work for some reason. @nshamit 

![image](https://user-images.githubusercontent.com/47103883/180647552-2110e996-54ad-44eb-9a61-3ad1406bee2f.png)

---

In step 2, is it necessary to include an input field to record the amount to be donated?
Is that only for users who have already logged in and have chosen which kind of donor they are?

The rest of the flow looks clear for users who haven't been logged in to the system.

**Comment by nshamit** [comment]
You can access the PDF here, alternatively: https://drive.google.com/drive/folders/1d0h0AUNRk-SPDAxw_GPQcf_aTxM061ZX

**Comment by nshamit** [comment]
In step 2, it is NOT necessary to provide that field to input a donation amount (for those who are NOT logged into the donor portal). Thanks for catching that. 

Individual donors will be able to donate through the new payment flow.

**Comment by nshamit** [comment]
Step 5: Connect to this page please: https://give.asia/charity/slredcross
