### ISSUE TITLE
Website Home Page Changes 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#239]
- [x] Add graphic above the aid packages (content to be provided)
- [ ] KEEP the My Pledges, Goal Pending and Goal Reached buttons the same. Don't change these buttons. The UI design has not been updated properly to reflect this. 

- [x] Navigation bar:
Home
About 
How to donate
Medical suppliers 
Newsroom

![Home Page Website](https://user-images.githubusercontent.com/44461004/180590126-0d1ebf36-e04f-4d49-b762-0657b46d39fc.jpeg)

**Comment by nshamit** [comment]
- [ ] As at July 27, 2022 we have been asked to remove the red footer @nipunsampath.

**Comment by nipunsampath** [comment]
> * [ ]  As at July 27, 2022 we have been asked to remove the red footer @nipunsampath.

I think this has been captured under https://github.com/LSFLK/MedicinesforLK/issues/278. I'm currently working on that under that issue. I think we should merge this as it is.
