### ISSUE TITLE
Website newsroom page changes 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#241]
On this page: https://donor-portal-medicinesfor-lk.vercel.app/news-room

- [x] Change title to media and news, and change placement of Media Contacts title as per image
- [x] Remove text about novel corona virus
- [x] KEEP existing content / contact information
- [x] Insert footer
- [x] Change cover image
![Newsroom](https://user-images.githubusercontent.com/44461004/180590351-2725abd2-3510-43e7-89a7-c27ea5251d3d.jpeg)

**Comment by anjula-sack** [comment]
I would like to work on this, can you assign me? @nshamit

**Comment by nshamit** [comment]
June 9th 2022
Sri Lanka Red Cross Society - Colombo Branch organised a blood donation camp in Colombo.

May 31st 2022
Singapore Red Cross donated medicines worth 68,500 SGD (approx. $50,000 USD).

**Comment by jayasanka-sack** [comment]
Tracked on https://github.com/LSFLK/MedicinesforLK/issues/371

**Comment by nshamit** [comment]
Just a thought, @jayasanka-sack @anjula-sack. Instead of having the info@redcross.lk email address in the newsroom section, I think that the email should be elixir@redcross.lk. Otherwise Red Cross will have to check multiple emails.

**Comment by anjula-sack** [comment]
> Just a thought, @jayasanka-sack @anjula-sack. Instead of having the [info@redcross.lk](mailto:info@redcross.lk) email address in the newsroom section, I think that the email should be [elixir@redcross.lk](mailto:elixir@redcross.lk). Otherwise Red Cross will have to check multiple emails.

This is fixed.
