### ISSUE TITLE
Update website content 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#250]
- [ ] Update website content using this document: https://docs.google.com/document/d/1-98fsyIGYGVjvTyV_C6IdrylLOXidWPfMr-Kg4hOxvA/edit?usp=sharing

**Comment by nshamit** [comment]
Hi Randila, can you fix the footer across all pages as well please:

- [ ] It should read  : "The Red Cross" 
- [ ] The display of the paragraph of text needs to change. Can you change this please as per the below:

                             You don't have to! 

The Red Cross team in collaboration with various teams 
on the ground are continuously reviewing the countries 
needs and prioritizing based on severity and criticality.

Your donation will be used to fund various aid packages.

                                   Donate to

**Comment by RandilaP** [comment]
Okay sure

**Comment by nshamit** [comment]
@RandilaP @jayasanka-sack we have now been instructed to remove the red footer from all pages by the content team.
