### ISSUE TITLE
Limit Progress bar width

### ISSUE THREAD

**Issue by dinuka-rp** [LSFLK/MedicinesforLK#255]
When the amount raised is higher than the goal, the progress bar goes beyond 100%

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/47103883/180823941-228f277d-1393-4624-bf73-8d5ed5f61f31.png">

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/47103883/180823050-70898d8a-52de-4fd5-89db-6f6e348f443d.png">

**Comment by dinuka-rp** [comment]
Should this be a backend validation or should it be controlled from the frontend?

**Comment by jayasanka-sack** [comment]
There should be validations from both ends. @dinuka-rp Could you please check the frontend? As I can remember, we are validating it on the frontend.

@anupama-pathirage Could you please assign someone for the backend?

**Comment by nshamit** [comment]
@manuranga please assign this to someone in the BE team

**Comment by jayasanka-sack** [comment]
This supposed to be fixed by https://github.com/LSFLK/MedicinesforLK/issues/265
