### ISSUE TITLE
API to retrieve list of available donors

### ISSUE THREAD

**Issue by ayeshLK** [LSFLK/MedicinesforLK#260]
**Is your feature request related to a problem? Please describe.**
Admin should be able to list up all the available donors in the admin-portal.

**Comment by ayeshLK** [comment]
Since `Users` endpoint of Asgardeo SCHIM API[1] does not support querying based on user group, we might need to use the `Groups` endpoint to retrieve users belonged to a particular user group. But, in the success response we only get limited information regarding the member of a particular user group. Refer to following sample response for user group search request:
```sh
{
   "totalResults":2,
   "startIndex":1,
   "itemsPerPage":2,
   "schemas":[
      "urn:ietf:params:scim:api:messages:2.0:ListResponse"
   ],
   "Resources":[
      {
         "id":"9741a27a-7772-465a-88cb-9289325cd73f",
         "displayName":"CUSTOMER-DEFAULT/SYSADMIN",
         "meta":{
            "created":"2022-07-28T10:08:19.372Z",
            "location":"https://api.asgardeo.io/t/ayesha/scim2/Groups/9741a27a-7772-465a-88cb-9289325cd73f",
            "lastModified":"2022-07-28T10:08:19.372Z"
         },
         "members":[
            {
               "$ref":"https://api.asgardeo.io/t/ayesha/scim2/Users/dac3c120-de07-4435-bc05-cd36dcd9cc1e",
               "display":"CUSTOMER-DEFAULT/ayesh9303@gmail.com",
               "value":"dac3c120-de07-4435-bc05-cd36dcd9cc1e"
            }
         ]
      }
   ]
}
```

@manuranga / @NipunaMarcus / @anupama-pathirage any thoughts ?

[1] - [https://wso2.com/asgardeo/docs/apis/scim2/](https://wso2.com/asgardeo/docs/apis/scim2/)

**Comment by NipunaMarcus** [comment]
We only need Donor First Name to be shown on admin aid package pledge status page. So If we can get those data it will be enough... Also here the delete functionality is for the pledge mapped for each donor so we only need to think about listing user named filtered by userid
