### ISSUE TITLE
594% pledge in aid packages view

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#265]
- [ ] 594% pledge in aid packages view. Should only be able to pledge 0-100% of the aid package value / need. 

![Screen Shot 2022-07-26 at 19 06 46](https://user-images.githubusercontent.com/44461004/181019549-c0cd6e15-af54-441d-9d78-3f5516f85659.jpg)

**Comment by anjula-sack** [comment]
so if the pledge is more than 100% should it show 100%? cuz the percentage is correct, right? It has received more than the pledge.

**Comment by nshamit** [comment]
It should only allow 100 percent of the funds to be pledged and display a message for anything over the 100per cent value.

**Comment by jayasanka-sack** [comment]
@anjula-sack I think this has to be validated in the backend (the frontend is already validating it) 
What might have happened is some have updated values from the database.


@anupama-pathirage @AmilaJ @manuranga 
Can we clean up those values for now?

**Comment by nshamit** [comment]
Agree, let's clean this up for the demo please.

**Comment by nshamit** [comment]
Still showing  the error. Take a look at the Goal figure. The goal is $20,000 USD, but when you add up the total cost of the medicines in the automatic post is 148,000+ Check this as the source of the error (why the percentage is 724%. 

![Screen Shot 2022-07-29 at 11 51 28](https://user-images.githubusercontent.com/44461004/181695952-b3b69de5-15bb-4fd2-b790-738351c40583.jpg)
![Screen Shot 2022-07-29 at 11 51 40](https://user-images.githubusercontent.com/44461004/181695964-182749c7-97a0-4e49-a561-1ee33e3250e3.jpg)

**Comment by nshamit** [comment]
- [ ] Validation: we should not let users come up with a total value that is less than the received amount
- [ ] Extra field for 'total value' @nshamit to speak to business stakeholders about this one. 
- [ ] Should not let users edit values after closing the package

**Comment by jayasanka-sack** [comment]
We need backend validations for the above.

**Comment by jayasanka-sack** [comment]
@manuranga Please assign someone from the BE team

**Comment by manuranga** [comment]
We keep getting `Already done Pledges amount exceeds the Aid Package Item Quantitiy Update` for any quantity update.

**Comment by nshamit** [comment]
as recorded in #468
