### ISSUE TITLE
/aidpackages/{id}/pledges Throws 500

### ISSUE THREAD

**Issue by jayasanka-sack** [LSFLK/MedicinesforLK#268]
**Is your feature request related to a problem? Please describe.**
/aidpackages/{id}/pledges resource throws following error:

`The field 'donorID' of type int cannot be mapped to the column 'DONORID' of SQL type 'VARCHAR'`

cc: @ManojLL @anupama-pathirage @AmilaJ

**Comment by jayasanka-sack** [comment]
@anupama-pathirage @AmilaJ could you please assign someone?

@manuranga is interested in working on this issue.

**Comment by NipunaMarcus** [comment]
this is due to the changes we did for the donor login fix... we only have one DB shared between dev and prod hence any database changes done will affect the both environment
