### ISSUE TITLE
Issue with donor pledging 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#280]
- [ ] The issue with pledging in the donor page is a type issue we are sending a number when the APIs expecting a string

**Comment by nshamit** [comment]
Pledging doesn’t work. Steps to reproduce:

1. Go to a pending pledge
2. Insert an amount
3. Click pledge button

**Comment by anjula-sack** [comment]
This issue has been fixed by @NipunaMarcus
