### ISSUE TITLE
Remove login from the footer

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#288]
- [ ] Login in footer behavior needs checking 
![Screen Shot 2022-07-28 at 10 35 28](https://user-images.githubusercontent.com/44461004/181424888-197cca6e-475d-40b9-bdad-f0f99deedb3b.jpg)

**Comment by jayasanka-sack** [comment]
Could you please elaborate more on this issue?

Is it to change the text to "Logout" if the user is logged in?

**Comment by nshamit** [comment]
This screen shows that you are logged in as per the top status, but the bottom footer says login, and doesn't seem connected:

![Screen Shot 2022-07-29 at 17 41 23](https://user-images.githubusercontent.com/44461004/181755822-7b444b07-2e39-46be-a9de-971f7a6eefc9.jpg)
