### ISSUE TITLE
In admin portal, an admin user cannot view or change the pledge status e.g. payment initiated, payment confirmed etc.

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#291]
In admin portal, an admin user cannot view or change the pledge status e.g. payment initiated, payment confirmed etc.

**Comment by anjula-sack** [comment]
Seems like we are not receiving the `donor` details from the backend.

**Comment by anjula-sack** [comment]
Previously `pledges/${pledgeID}`  received the donor now it doesn't. 

```
{
    "pledgeID": 21,
    "packageID": 2,
    "donorID": "2",
    "amount": 0,
    "status": "Payment Confirmed"
}
```

@nshamit

**Comment by manuranga** [comment]
This looks like the exact commit where it got removed 
https://github.com/LSFLK/MedicinesforLK-AdminAPI/commit/93adb95974b328dd673cf4779a9d74add2d456a2
@AmilaJ was removing `pledge.donor = check getDonor(pledge.donorID);` an accident or is that intentional?

**Comment by nshamit** [comment]
Pledge statuses do not show, but are showing aid package statuses. https://github.com/LSFLK/MedicinesforLK/issues/291 . Could be that something changed from this issue: https://github.com/LSFLK/MedicinesforLK/issues/198 When clicking on pledges button, the page goes blank, need to go back and refresh to get aid packages page again.

**Comment by anjula-sack** [comment]
> Pledge statuses do not show, but are showing aid package statuses. #291 . Could be that something changed from this issue: #198 When clicking on pledges button, the page goes blank, need to go back and refresh to get aid packages page again.

Seems like the missing donor thing is not yet fixed from the BE

**Comment by NipunaMarcus** [comment]
Currently as we are using the asgardeo as the user store these details are not available in our DB ... So Ayesh is working on getting these details from the asgardeo .... Till that fix is there Shall we show the donorID as the orgName ... for now? then page failure goes away?

**Comment by nshamit** [comment]
Proceed. Demo is in 40 mins.

**Comment by anjula-sack** [comment]
> Currently as we are using the asgardeo as the user store these details are not available in our DB ... So Ayesh is working on getting these details from the asgardeo .... Till that fix is there Shall we show the donorID as the orgName ... for now? then page failure goes away?

yes we can show the ID

**Comment by jayasanka-sack** [comment]
https://github.com/LSFLK/MedicinesforLK/pull/304
