### ISSUE TITLE
Automatic posts in detailed aid package post in two different orders 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#301]
- [ ] Automatic posts in detailed aid package post happens 1) when the package is in draft mode AND 2) when the package becomes published, AND 3) medicines are in two different orders in both automatic posts. 

To reproduce: 
1. Create aid package in draft state - see auto post (the order of medicines in the automatic post is incorrect)
2. Move the aid package status to "published" by checking the box in aid package details page (the order of the medicines in the automatic post is correct) 

![Screen Shot 2022-07-29 at 11 45 25](https://user-images.githubusercontent.com/44461004/181695403-8735a47f-78f2-4a08-8ed0-6b38408cc770.jpg)
![Screen Shot 2022-07-29 at 11 45 57](https://user-images.githubusercontent.com/44461004/181695418-d986fc84-98ce-49b1-8367-a62f4ba92be9.jpg)

**Comment by manuranga** [comment]
Given the dead line its better to first fix the issue in frontend if that is lower effort.

**Comment by manuranga** [comment]
Above should temp fix it form the UI. Auto post is create only if it's created in published state not in draft state. I hope this the expected outcome.
1) But I noticed another thing, if I jump past published directly form draft, I don't see the auto post. Is that an issue? @nshamit 
If so let's create a separate issue.

2) If above fix is correct, let's create a separate issue to move the auto posting to backend, and close this.

**Comment by nshamit** [comment]
All posts need to go through the published state. Even if they don't get saved as draft first they must go through the published state. So the post needs to be there at the time the aid package moves into the published state.
