### ISSUE TITLE
Able to create aid package with quantity of medicine in excess of max quantity available from supplier 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#302]
- [ ] Able to create aid package with quantity of medicine in excess of max quantity available from supplier 
![Screen Shot 2022-07-29 at 11 56 57](https://user-images.githubusercontent.com/44461004/181696799-7ed1686b-6078-4669-a8c8-185250301145.jpg)

![Screen Shot 2022-07-29 at 11 56 37](https://user-images.githubusercontent.com/44461004/181696783-ddc1a097-0e15-4ff9-a386-188ef925a2a6.jpg)

**Comment by nshamit** [comment]
Needs to be checked on the BE as well.

**Comment by udda1996** [comment]
In the BE we have already added the check to avoid this. https://github.com/LSFLK/MedicinesforLK-AdminAPI/blob/main/service.bal#L104

**Comment by udda1996** [comment]
We need to add a validation to assure that the Goal amount is still greater or equal than the received amount after an edit (decrease) in the quantity of an aid package item.

**Comment by nshamit** [comment]
@udda1996 @jayasanka-sack @anjula-sack  can we close this

**Comment by udda1996** [comment]
We have avoid creating packages with amounts more than the remaining quantity form the supplier.
