### ISSUE TITLE
Able to delete an aid package medicine from aid package details view when the status of package is "ordered"

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#303]
Able to delete an aid package medicine from aid package details view when the status of package is "ordered"

![Screen Shot 2022-07-29 at 12 00 48](https://user-images.githubusercontent.com/44461004/181697369-dabb6d6c-ce9f-44fb-9c32-709813b68127.jpg)
![Screen Shot 2022-07-29 at 12 00 58](https://user-images.githubusercontent.com/44461004/181697384-23958028-3aa7-4733-bf71-191073f19581.jpg)

**Comment by nshamit** [comment]
Should only be allowed in "Draft" and "published" states.
BE validation needed as well (as a best practice)

**Comment by dinuka-rp** [comment]
@nshamit should _edit_ be restricted similarly as well?

**Comment by nshamit** [comment]
We should be able to edit or delete in the draft or published status. This should be restricted from awaiting payment onwards.

**Comment by jayasanka-sack** [comment]
We need to validate this on the Backend as well.

**Comment by manuranga** [comment]
```ballerina
function deleteAidPackageItem(int packageId, int packageItemId) returns error? {
    _ = check dbClient->execute(`DELETE AID_PACKAGE_ITEM FROM AID_PACKAGE_ITEM INNER JOIN AID_PACKAGE ON
    AID_PACKAGE_ITEM.PACKAGEID=AID_PACKAGE.PACKAGEID WHERE
    AID_PACKAGE_ITEM.PACKAGEID=${packageId} AND PACKAGEITEMID=${packageItemId} AND (STATUS="Draft" OR STATUS="Published");`);
}
```
I tested above to prevent deletion. It works. But preventing editing seems more complicated since it happens in multiple queries.

**Comment by manuranga** [comment]
Above pr should fix the backend part, but I don't see the frountent part is working for the delete (edit part of the frontend works)
@dinuka-rp can you please look into it.

**Comment by manuranga** [comment]
I to a pull looks like frontend if fixed, maybe I tested with older UI. removing [dinuka-rp](https://github.com/dinuka-rp).

**Comment by dinuka-rp** [comment]
Yeah, it uses the same logic. Thanks for checking and confirming @manuranga

**Comment by nshamit** [comment]
@manuranga @dinuka-rp what's the status of this issue?
