### ISSUE TITLE
Can't pledge for an Aid Package

### ISSUE THREAD

**Issue by jayasanka-sack** [LSFLK/MedicinesforLK#306]
**Is your feature request related to a problem? Please describe.**
Currently, nothing happens when trying to pledge for a package. 

`{donorID}/aidpackages/{packageID}/pledge` throws a CORS error

**Comment by jayasanka-sack** [comment]
It seems `elixir.redcross.lk` domain isn't whitelisted. @manuranga could you please assign someone from the team?

**Comment by NipunaMarcus** [comment]
This now should work

**Comment by manuranga** [comment]
https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/error-handling/

**Comment by NipunaMarcus** [comment]
This happened due to the wrong configuration values for the BE DB. 

Issue was identified by looking at the Choreo observability logs.

This is now fixed in the development and production deployment of the donor API

**Comment by nshamit** [comment]
@jayasanka-sack
