### ISSUE TITLE
Aid package shows $0 pledged, but has moved to the Goal Reached section. 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#307]
- [ ] Aid package shows $0 pledged, but has moved to the Goal Reached section. 
![Screen Shot 2022-07-29 at 17 25 59](https://user-images.githubusercontent.com/44461004/181753654-3f90ee59-c535-4557-85fb-d74f36df26ae.jpg)

![Screen Shot 2022-07-29 at 17 25 45](https://user-images.githubusercontent.com/44461004/181753640-b955f92e-ce26-462b-adb1-ffc3bc19cb21.jpg)

**Comment by jayasanka-sack** [comment]
@dinuka-rp After your PR the validation message is showing on every completion step. ex: we don't need it when moving from shipped to delivered

It should display the confirmation only when changing to a completion state from draft or Published
