### ISSUE TITLE
Change the hero image of Single aid package view

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#309]
- [ ] The ability to change the image associated with each aid package in the admin portal so that they are relevant to the medicine or donor organization. 

This image is shown on the donor portal side. Currently we have no way of selecting that image on the admin portal side. The images are hard coded. 
![Screen Shot 2022-07-30 at 09 45 31](https://user-images.githubusercontent.com/44461004/181872014-e23e95c9-5cab-458a-b497-5cc55cfa2b83.jpg)

**Comment by jayasanka-sack** [comment]
I will update this issue once I receive the image
