### ISSUE TITLE
Inclusion of donor information to be shown on donor portal side of aid package details 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#310]
**The rationale behind this functionality is that the system helps prevent DUPLICATION of fulfillment of the need. We need to log all aid packages, even those not donated/fulfilled by the Red Cross to provide greater transparency and show the global community that the need is not being duplicated, and money is not being wasted. The Red Cross will invite these organizations to use the system using separate admin credentials. ** 

- [ ] Inclusion of "Created by" information to be entered in on the admin portal side, and shown on donor portal side of aid package details. The Created by field should be located UNDER the title, and ABOVE the description of the aid package. 

The login credential should select the "Created by" information automatically. E.g. If an aid package is "created by" the Sri Lankan Physicians of North America, when someone from that organization logs in, the admin portal should auto select this detail when they create an aid package. 

Similarly, when a Red Cross admin creates an aid package, "created by" should automatically state "Red Cross". 

![Screen Shot 2022-07-30 at 09 54 14](https://user-images.githubusercontent.com/44461004/181872223-27793efb-ae7f-4a9c-87f0-b952a782e803.jpg)

The user from e.g. the Sri Lankan Physicians of North America should be able to:

* provide an organization email to the Red Cross/LSF and obtain admin credentials 
* upload supplier information when e.g. the supplier name is not in the system. 
* create aid packages of medicines and medical supplies and record the beneficiary details. 
* provide details on the status of the aid packages.

**Comment by nshamit** [comment]
hold on this. getting clarity from business stakeholders.

**Comment by nshamit** [comment]
@NipunaMarcus do we need to reassign this issue?

**Comment by manuranga** [comment]
@ayeshLK I merged and rolled out the changes, I am seeing following error in donor dev portal:
```
Error while executing SQL query: SELECT AID_PACKAGE.PACKAGEID, NAME, DESCRIPTION, 
                                                                    AID_PACKAGE.STATUS, AID_PACKAGE.CREATEDBY as 'createdBy', PLEDGE.AMOUNT 
                                                                    FROM AID_PACKAGE INNER JOIN PLEDGE 
                                                                        ON AID_PACKAGE.PACKAGEID = PLEDGE.PACKAGEID 
                                                                    WHERE AID_PACKAGE.STATUS!= ?  AND DONORID= ? . Column 'DONORID' in where clause is ambiguous.
```

**Comment by manuranga** [comment]
Fixed above. @dinuka-rp frontend part can be started now.

**Comment by dinuka-rp** [comment]
@manuranga @ayeshLK thanks,
Was the existing API of GET aidpackage details updated to send the required info?
