### ISSUE TITLE
API to filter out donors according to the `Pledges` for a particular `AidPackage`

### ISSUE THREAD

**Issue by ayeshLK** [LSFLK/MedicinesforLK#312]
**Is your feature request related to a problem? Please describe.**
Admin should be able to filter out donors based on the pledges for a particular aid-package.

**Describe the solution you'd like**
Provide a REST resource to filter-out donors based on the pledges for a particular aid-package. 
This API resource would function as follows:
- Input: aid-package ID (can be a query parameter or a path parameter)
- Filtering logic:
  - Find the pledges for a particular aid-package based on the aid-package ID
  - Find the donor IDs for the filtered pledges
  - Retrieve user details related to filtered donor IDs from Asgardeo SCHIM API

**Comment by ayeshLK** [comment]
I am currently trying to filter out list of users using SCHIM user search API [1]. But the mentioned API does not support any bulk search operations. If that is the case then will have to query the SCHIM API for each and every donor to get the details. And that means there will be multiple requests to the SCHIM API, per one Admin API request. @manuranga / @anupama-pathirage  any thoughts on how we could improve this ?

[1] - [https://wso2.com/asgardeo/docs/apis/scim2/](https://wso2.com/asgardeo/docs/apis/scim2/)

**Comment by manuranga** [comment]
In SCIM spec it is possible by saying something like `/Users?filter=id eq 293 or id eq 322`. But unfortialy Asgadeo dosn't seems to support it. Form the doc it looks like only supported options are  ‘Ew’, ‘Eq’, ‘Co’, ‘Sw’, ‘and’.

https://is.docs.wso2.com/en/latest/develop/scim2-rest-apis/#/Users%20Endpoint/getUser

It looks like we'll have to get one by one or get all user donor and filer in our side.

**Comment by ayeshLK** [comment]
If we have to get one by one that means at least 10+ requests should be initiated to SCHIM API before responding to Admin API request. I think this is not scalable. 

Then the only option is to get all the donors and filter in our side. This means we have to query the SCHIM API beforehand and store the donor details in a cache/db and query that. I think the DB approach is better. 

@anupama-pathirage / @manuranga / @NipunaMarcus  WDYT ?

**Comment by manuranga** [comment]
Shall we first do a version where we just get on demand and filter in during the request. Then we can look at how slow it is decide on caching.
