### ISSUE TITLE
Align the navbar with page content

### ISSUE THREAD

**Issue by jayasanka-sack** [LSFLK/MedicinesforLK#317]
**Is your feature request related to a problem? Please describe.**
The current navbar is not properly aligned with the content. 
<img width="1224" alt="Screenshot 2022-07-31 at 22 00 36" src="https://user-images.githubusercontent.com/33048395/182036147-413ac15d-984b-43ea-9c70-6c66b2a646ec.png">

**Describe the solution you'd like**
Please re-allign the navbar

**Comment by dinuka-rp** [comment]
<img width="1617" alt="image" src="https://user-images.githubusercontent.com/47103883/182166457-14afae26-fd30-47f2-9574-61f20a987f18.png">
@jayasanka-sack is this alright? The way the navbar and content have been designed, with auto widths & margins, it's a little tricky to align it.

Might need some help from a CSS guru here 🥲

**Comment by jayasanka-sack** [comment]
The logo and the login button should be aligned with the content.

**Comment by dinuka-rp** [comment]
ohh! got it.
I'll see what I can do.

I was trying to align only the nav menu items

**Comment by jayasanka-sack** [comment]
I'll fix this.
