### ISSUE TITLE
A published aid package moves back to draft status when the description is edited in the admin portal 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#329]
- [ ] A published aid package moves back to draft status when the description is edited in the admin portal 

![Screen Shot 2022-08-02 at 09 29 28](https://user-images.githubusercontent.com/44461004/182289036-9f82e47f-07d0-4c20-97f2-406b4354d275.jpg)

![Screen Shot 2022-08-02 at 09 29 44](https://user-images.githubusercontent.com/44461004/182289044-9bdf08c3-f9f7-4b7a-8d52-5d966618eb50.jpg)

**Comment by jayasanka-sack** [comment]
This is a FE issue. I'll look into this.

**Comment by jayasanka-sack** [comment]
Steps to reproduce:

1. Open a draft package
2. Change state to published
3. Change the description and hit save

**Comment by jayasanka-sack** [comment]
We need a BE validation as well (need to restrict moving backwards)

**Comment by nshamit** [comment]
status on this issue please?

**Comment by manuranga** [comment]
Not fixed in backend.
