### ISSUE TITLE
Admin portal status message needs to change 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#330]
- [ ] Admin portal status message needs to change 

![Screen Shot 2022-08-02 at 09 49 07](https://user-images.githubusercontent.com/44461004/182290962-79a2333e-2311-457f-a310-bf9686c9d15d.jpg)

Text should read:

Statuses can only be updated forward towards completion

**Comment by jayasanka-sack** [comment]
Hi Sherazad, there are two confirmation messages. 
This is related to the following issue:
https://github.com/LSFLK/MedicinesforLK/issues/307#issuecomment-1202571840
