### ISSUE TITLE
When medicines are allocated, the total remaining need number changes, but not the supplier wise max number 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#332]
- [ ] When medicines are allocated, the total remaining need number changes, but not the supplier wise max number. This means that if you have two suppliers, you don't know which supplier quantity has been reduced, and you have to guess which amount to enter into the next aid package against a supplier. 

![Screen Shot 2022-08-02 at 10 17 10](https://user-images.githubusercontent.com/44461004/182294097-5dad2fc4-282c-4cde-b7b7-87e4e9b46028.jpg)

**Comment by jayasanka-sack** [comment]
#302

**Comment by jayasanka-sack** [comment]
TODO: @udda1996 add a comment

**Comment by udda1996** [comment]
@jayasanka-sack with the PR [#60](https://github.com/LSFLK/MedicinesforLK-AdminAPI/pull/60) we have included a new field `remainingQuantity` which refers to the unassigned amount in each quotation. This can be used to track supplier wise remaining quantity so users can have an idea about the amounts remaining to assign from each supplier. 
![182294097-5dad2fc4-282c-4cde-b7b7-87e4e9b46028](https://user-images.githubusercontent.com/66210480/183423283-8478a692-cc98-4e40-bb99-101c92c7a9f6.jpg)
