### ISSUE TITLE
Images on the home page are disappearing once the page is loaded

### ISSUE THREAD

**Issue by jayasanka-sack** [LSFLK/MedicinesforLK#336]
**Is your feature request related to a problem? Please describe.**
Images on the home page are disappearing once the page is loaded. (It's happening only on the https://elixir.redcross.lk/ domain)

Steps to reproduce: 
1. Visit https://elixir.redcross.lk/
2. Wait until the page is loaded
3. See redcross logo and other logos disappear

**Comment by jayasanka-sack** [comment]
@anjula-sack The issue is still there. However it works fine on the vercel link. (it has the same content)

https://donor-portal-medicinesfor-lk.vercel.app/

**Comment by jayasanka-sack** [comment]
This issue only occurs on chrome. works fine on safari. If you right click, there's an option to load the image.
<img width="405" alt="Screenshot 2022-08-03 at 21 47 30" src="https://user-images.githubusercontent.com/33048395/182658656-59de6de9-0047-4c46-98bc-46a356c9a262.png">

**Comment by anjula-sack** [comment]
> This issue only occurs on chrome. works fine on safari. If you right click, there's an option to load the image. <img alt="Screenshot 2022-08-03 at 21 47 30" width="405" src="https://user-images.githubusercontent.com/33048395/182658656-59de6de9-0047-4c46-98bc-46a356c9a262.png">

we can try moving the `assets` to the `src`

**Comment by jayasanka-sack** [comment]
> >
> we can try moving the `assets` to the `src`

@anjula-sack already done.

**Comment by anjula-sack** [comment]
> > > 
> > 
> > 
> > we can try moving the `assets` to the `src`
> 
> @anjula-sack already done.

A temporary solution might be hosting the images somewhere

**Comment by jayasanka-sack** [comment]
Yeah, but there should be a reason for this issue

**Comment by jayasanka-sack** [comment]
I'm not sure what the root cause is but it comes from the Asgardeo SDK. 

It occurs when you provide redirection URLs (No need to match with the current domain. Even a random string works). Currently, redirection URLs are provided on the https://elixir.redcross.lk/ deployment. That's why it only occurs in that domain. 

To reproduce this locally,
1. create `.env.local` file as instructed on the [readme](https://github.com/LSFLK/MedicinesforLK/blob/development/README.md). 
2. Provide some values to redirect URLs. (You don't need to provide other values)

**Comment by nipunsampath** [comment]
The root cause of this appears to be the silent sign-in attempt.  Based on what I have seen I think this is what happens.

1. Images are downloaded when the application loads for the first time. 
2. Asgardeo tries to sign in silently and gets redirected back to the redirect URL.
3. The application tries downloading the images again, but Chrome cancels the image requests for some reason. 
(It does cancel requests for base64 encoded images, that is why only some images are displayed)

I have disabled the silent sign-in functionality as a hotfix.

**Comment by jayasanka-sack** [comment]
The issue is temporarily fixed by using inline images: https://github.com/LSFLK/MedicinesforLK/pull/360 

Keeping this issue open until we find a proper solution.

Thanks for the investigation @nipunsampath! We are so glad to have you on the team!

**Comment by nshamit** [comment]
status on this issue please?

**Comment by nipunsampath** [comment]
> status on this issue please?

I reported the issue to the Asgardeo team. I will post here when there are new updates.
