### ISSUE TITLE
Separate the dev environment

### ISSUE THREAD

**Issue by jayasanka-sack** [LSFLK/MedicinesforLK#351]
We need to separate things out from Choreo side, Vercel, Adgadeo side and DB side.

**Comment by jayasanka-sack** [comment]
@manuranga Can we close this issue now?

**Comment by manuranga** [comment]
I only did the admin portal, we still to do donor portal.

**Comment by nshamit** [comment]
shall we get this done by thurs 18th aug?

**Comment by dinuka-rp** [comment]
Once #418 is fixed, the dev environment needs to have token security activated again from Choreo.
Then, this can be closed.
