### ISSUE TITLE
Edit button for create aid package next to save as draft and publish

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#354]
- [x] Edit button for create aid package next to save as draft and publish. This is to help user behavior since they cannot edit an aid package title after it is published.

**Comment by jayasanka-sack** [comment]
Fix: Remove the publish button

**Comment by jayasanka-sack** [comment]
@nshamit Could you please elaborate more on this?

**Comment by nshamit** [comment]
@jayasanka-sack 
- [ ] In addition to the Publish and Save as draft buttons, include an Edit button to immediately direct users to edit the package name and the description. 
- [ ] Also change the order of the buttons. The order should be : 1) Edit 2) Save as draft 3) Publish 
- [ ] Check whether the save as draft button works. I could not save as draft, and lost the packages I kept creating.

**Comment by jayasanka-sack** [comment]
@anjula-sack Could you please look into the above issue with your current task?

**Comment by jayasanka-sack** [comment]
I think a proper solution to address the issue might be to make the section collapsible. So the inputs would be visible by default.

@anjula-sack What do you think?

**Comment by anjula-sack** [comment]
> I think a proper solution to address the issue might be to make the section collapsible. So the inputs would be visible by default.
> 
> @anjula-sack @nshamit What do you think?

yeah but I went through the code with the current implementation button is the easiest

**Comment by jayasanka-sack** [comment]
We can't publish/save without editing the title, right? Therefore editing is not a choice it's a necessity.

**Comment by nshamit** [comment]
As long as we give the user a visual cue to press the edit button and change the name of the aid package, i'm fine with the easiest solution you can come up with.
