### ISSUE TITLE
Not able to create an aid package without changing its name first.

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#359]
- [ ] Not able to create an aid package without changing its name first. Will throw an error stating that 'something went wrong'.

**Comment by jayasanka-sack** [comment]
Tracked at https://github.com/LSFLK/MedicinesforLK/issues/300

@anjula-sack Could you please make the inputs visible by default?

**Comment by jayasanka-sack** [comment]
Tracked at https://github.com/LSFLK/MedicinesforLK/issues/354

Closing the issue
