### ISSUE TITLE
Can edit comments in the admin portal once posted. Needs to be non-editable once posted. 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#362]
- [ ] Can edit comments in the admin portal once posted. Needs to be non-editable once posted.

**Comment by jayasanka-sack** [comment]
Would you mind explaining the reason? I think it's nice to have an option to edit a comment.

**Comment by nshamit** [comment]
We decided to let comments remain editable because comments are public-facing and need to be worded appropriately balancing transparency and security concerns.
