### ISSUE TITLE
Shortcut to update donor pledge status, current workflow is not natural and is taxing on the user 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#368]
- [ ] Shortcut to update donor pledge status, current workflow is not natural and is taxing on the user

**Comment by jayasanka-sack** [comment]
Is this issue related to https://github.com/LSFLK/MedicinesforLK/issues/198?

**Comment by nshamit** [comment]
@dinuka-rp, status on this issue please?

**Comment by dinuka-rp** [comment]
@nshamit working on this, will try to complete and push the changes today

**Comment by nshamit** [comment]
HI @dinuka-rp is this taken care of ?

**Comment by dinuka-rp** [comment]
@nshamit I'm holding on this issue since it can't be tested without the GET pledges API, which doesn't work as mentioned in #376
