### ISSUE TITLE
When deleting an aid package which is saved as draft, the quantity is not returned to the total quantity required after deletion. Cannot create the aid package after that.

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#373]
- [ ] When deleting an aid package which is saved as draft, the quantity is not returned to the total quantity required. 

![Screen Shot 2022-08-07 at 19 38 46](https://user-images.githubusercontent.com/44461004/183294840-a7fc3253-fb9d-4333-81a3-752e8656cad0.jpg)

**Comment by jayasanka-sack** [comment]
Steps to reproduce:

1. Create aid package as draft
2. Delete the package
3. Try to create a package.

**Comment by nshamit** [comment]
@anjula-sack @udda1996 any updates on this?

**Comment by anjula-sack** [comment]
> @anjula-sack @udda1996 any updates on this?

This needs to be handled from the backend. @udda1996 can you take a look again?
