### ISSUE TITLE
GET /aidpackages/{id}/pledges throws 403

### ISSUE THREAD

**Issue by jayasanka-sack** [LSFLK/MedicinesforLK#376]
`GET /aidpackages/{id}/pledges` (Admin API) throws 403 with the following content:

```json
{
   "schemas":[
      "urn:ietf:params:scim:api:messages:2.0:Error"
   ],
   "detail":"Operation is not permitted. You do not have permissions to make this request.",
   "status":403
}
```

**Comment by nipunsampath** [comment]
@jayasanka-sack was this issue fixed somewhere? I tried to reproduce this in prod yesterday, but couldn't. I got a 401 error code on some pledges in my local setup though.

**Comment by manuranga** [comment]
It appered without us doing any change in the first place. So it could be an intermittent issue in Asgadeo. @nipunsampath is looking into it.

**Comment by dinuka-rp** [comment]
Closing this since it works now @manuranga
