### ISSUE TITLE
Update the Donate now page with mobile responsiveness.

### ISSUE THREAD

**Issue by kanushka** [LSFLK/MedicinesforLK#383]

**Comment by dinuka-rp** [comment]
@RandilaP would you like to take this issue up?

**Comment by jayasanka-sack** [comment]
Duplicate: https://github.com/LSFLK/MedicinesforLK/issues/386

**Comment by dinuka-rp** [comment]
@jayasanka-sack Isn't this a separate page?

**Comment by dinuka-rp** [comment]
@nipuna777 would you like to work on this?

**Comment by nipuna777** [comment]
@dinuka-rp I think I wrote this page to be responsive.

We should be able to close this off?

Desktop
![image](https://user-images.githubusercontent.com/5859290/185405305-6d16c76a-f006-427d-af42-094305c33a66.png)

Mobile
![image](https://user-images.githubusercontent.com/5859290/185405400-336048eb-abc7-4208-97cd-7be7c8ab4681.png)

**Comment by dinuka-rp** [comment]
Oh cool 👌🏾 we can close this then
Thanks @nipuna777
