### ISSUE TITLE
In the prod environment,  a pledge is not being registered in the pledge status area 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#389]
- [ ] In the prod environment,  pledges are not being registered in the pledge status area. I made one pledge using Tharaka Samarasinghe's donor account, for the full amount. 

![Screen Shot 2022-08-09 at 09 54 56](https://user-images.githubusercontent.com/44461004/183564186-d8f09e05-e782-4cbb-84ed-5afe98ece853.jpg)

![Screen Shot 2022-08-09 at 09 57 43](https://user-images.githubusercontent.com/44461004/183564282-dab790d9-0721-4889-a373-738a715dd5d6.jpg)

**Comment by jayasanka-sack** [comment]
Tracked at: https://github.com/LSFLK/MedicinesforLK/issues/376
