### ISSUE TITLE
Make the hero image component mobile responsive

### ISSUE THREAD

**Issue by jayasanka-sack** [LSFLK/MedicinesforLK#391]
The [hero section component ](https://github.com/LSFLK/MedicinesforLK/blob/development/donor-portal/src/pages/layout/hero-section/index.tsx) is not mobile responsive. Please make it mobile-friendly. 

Suggestions:

Add padding to text and reduce the font size on mobile devices.
ex:
<img width="464" alt="image" src="https://user-images.githubusercontent.com/33048395/183806892-a42c702d-a855-4cb1-9bb2-3c0e80e79805.png">

**Comment by jayasanka-sack** [comment]
@kanushka Feel free to assign someone to this issue.  😊

**Comment by dinuka-rp** [comment]
@ManojLL would you like to take this issue up?

**Comment by ManojLL** [comment]
@dinuka-rp  I'm working on this.
