### ISSUE TITLE
Fix invalid email link in the footer

### ISSUE THREAD

**Issue by jayasanka-sack** [LSFLK/MedicinesforLK#396]
the email link is invalid. The correct one should be `mailto:elixir@redcross.lk`

https://github.com/LSFLK/MedicinesforLK/blob/b407b12e94474a1dfec88ee37758b734f643eef2/donor-portal/src/components/footer/index.tsx#L13

**Comment by gajindubandara** [comment]
I would like to work on this issue

**Comment by jayasanka-sack** [comment]
Sure! go ahead @gajindubandara !
