### ISSUE TITLE
CSV file not being uploaded in the Suppliers tab

### ISSUE THREAD

**Issue by DilinaBandara** [LSFLK/MedicinesforLK#441]
**Is your feature request related to a problem? Please describe.**
The CSV file does not get uploaded after choosing the file

**Describe the solution you'd like**
The CSV file needs to get uploaded after being selected

**Additional context**
![image](https://user-images.githubusercontent.com/104125359/187274380-fcee49cc-c7e9-4583-ae52-c1b43f3299af.png)

**Comment by dinuka-rp** [comment]
This issue was fixed when the new CSV file was used.
