### ISSUE TITLE
CSV file not being uploaded in the Needs tab

### ISSUE THREAD

**Issue by DilinaBandara** [LSFLK/MedicinesforLK#442]
**Is your feature request related to a problem? Please describe.**
The CSV file does not get uploaded after choosing the file

**Describe the solution you'd like**
The CSV file needs to get uploaded after being selected

**Additional context**
![image](https://user-images.githubusercontent.com/104125359/187274457-c9b72eb2-9d53-4445-af77-fac516c99aa7.png)

**Comment by dinuka-rp** [comment]
This issue was fixed when the new CSV file was used.
