### ISSUE TITLE
When you click the save as draft button, you require a cancel button as well as OK button in the pop up message 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#462]
- [ ] When you click the save as draft button, you require a cancel button as well as OK button in the pop up message as users may not edit the details before they save as draft. Including this back/cancel button will ensure they can avoid this. 

![Screen Shot 2022-09-07 at 12 09 09](https://user-images.githubusercontent.com/44461004/188806928-fb2ee0ec-433e-4fdb-86b1-750b2b0dc35a.jpg)

**Comment by nshamit** [comment]
@dinuka-rp can you take care of this one?

**Comment by dinuka-rp** [comment]
Blocked by #514

**Comment by dinuka-rp** [comment]
Closing the issue since the current behavior works as expected. A package won't be created if the name hasn't been given
