### ISSUE TITLE
Remaining need is showing as minus values

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#463]
- [ ] Total assigned quantity must be less than quantity needed. Aid packages could still be created in excess of quantity available. Remaining need is showing as minus values.

Need to check if values when edited in the detailed aid package view are causing this or if values in the create aid package view are being allowed. 

![IMG_5267](https://user-images.githubusercontent.com/44461004/188861708-fd597994-5da3-491c-a9dc-f1f03bc30a52.jpg)

**Comment by akbandara** [comment]
We think this is a data issue, due to needs being updated with lower quantities.  Needs to be retested once other changes are pushed to production.

**Comment by nshamit** [comment]
@akbandara @anjula-sack @DilinaBandara @dinuka-rp can we retest this?

**Comment by nshamit** [comment]
closing issue. related to needs / supplier quantities being changed.
