### ISSUE TITLE
Expiry date is not correctly formatted. Should be DD/MM/YY. Is currently MM/DD/YY

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#464]
- [ ] Expiry date is not correctly formatted. Should be DD/MM/YY. Is currently MM/DD/YY.

![Screen Shot 2022-09-07 at 12 20 25](https://user-images.githubusercontent.com/44461004/188809138-d2c71ac8-f35d-48f2-8b30-be471c4a4153.jpg)
![Screen Shot 2022-09-07 at 12 21 29](https://user-images.githubusercontent.com/44461004/188809162-6d0a388c-9747-4d33-9bd3-51acaae3090e.jpg)

**Comment by anjula-sack** [comment]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/43912578/188922053-2ba3a5d7-10ae-4074-b326-61a9bab953da.png">
This is the payload. Seems like the month and day are swapped. This should be handled from the BE.
cc: @manuranga
