### ISSUE TITLE
Error message in prod when uploading supply quotation form, only experienced by one user. 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#472]
Error message in prod when uploading supply quotation form, only experienced by one user.:

![Screen Shot 2022-09-12 at 17 05 04](https://user-images.githubusercontent.com/44461004/189813101-39b80afb-9948-4fd4-8aac-c7684f385294.jpg)

**Comment by manuranga** [comment]
From error logs it looks like this is the line that throws the error https://github.com/LSFLK/MedicinesforLK-AdminAPI/blob/336e8f9efd7731aeae1b3dbc84c444ab9aab9fda/csv_processor.bal#L97

**Comment by manuranga** [comment]
Basically it looks like there was a period that dosn't follow the format `mm yyyy`.

**Comment by nshamit** [comment]
We understood that this was due to accidentally edited data in the supply quotation csv form. We sent the user the correct CSV file. This error did not persist.
