### ISSUE TITLE
Dev env : Medicines from same supplier getting populated in aid packages relating to that supplier 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#473]
- [ ] Dev env : Medicines from same supplier getting populated in aid packages relating to that supplier 

First Aid package was for only Erythropoeitin (Sept 2022), from Zydus, BUT it also contains Gauze.
![Screen Shot 2022-09-13 at 12 28 51](https://user-images.githubusercontent.com/44461004/189832483-c80b7305-809c-497b-978e-7f0a9be48542.jpg)

Second Aid package was for only Gauze (Aug 2022), from Zydus, BUT it also contains Erythropoeitin. 
![Screen Shot 2022-09-13 at 12 29 06](https://user-images.githubusercontent.com/44461004/189832841-305d139d-7980-43d3-a284-2101eb578496.jpg)

Desired outcome:

- [ ] Aid packages can contain medicines from any period (August, September, October, even June, July), as long as they are from the same supplier (Zydus).

**Comment by nshamit** [comment]
Outcomes need to be:
1. Grouping items from one supplier, regardless of the period in one aid package. Fix #478, and we will not need to fix this issue, I think.

**Comment by anjula-sack** [comment]
Fixed by https://github.com/LSFLK/MedicinesforLK/pull/493
