### ISSUE TITLE
Dev env: Cannot save edits to medicine quantities in the admin portal detailed aid package view 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#475]
- [ ] Dev env: Cannot save edits to medicine quantities in the admin portal detailed aid package view. 

![Screen Shot 2022-09-13 at 12 47 54](https://user-images.githubusercontent.com/44461004/189836047-4d3a5be2-a129-4a49-9e70-cd3aa3118ee5.jpg)

**Comment by nshamit** [comment]
related to the timeout issue, mos tlikely.

**Comment by akbandara** [comment]
Timeout issues now resolved .. reducing priority of this issue

**Comment by nshamit** [comment]
@DilinaBandara can you test this please? and add this to the list of test cases/ scenarios.

**Comment by DilinaBandara** [comment]
@nshamit I keep receiving this message when attempting to edit quantity and save it

![image](https://user-images.githubusercontent.com/104125359/194142576-e990eed9-2353-41d6-b2b9-f8d2922b7c39.png)

**Comment by DilinaBandara** [comment]
Can you take a look at this @anjula-sack

**Comment by anjula-sack** [comment]
Duplicated issue https://github.com/LSFLK/MedicinesforLK/issues/468
