### ISSUE TITLE
Request return 401 the first time but succeed the second try

### ISSUE THREAD

**Issue by manuranga** [LSFLK/MedicinesforLK#477]
<img width="744" alt="Screenshot 2022-09-13 at 10 04 13 PM" src="https://user-images.githubusercontent.com/1686124/189957980-3172546f-764c-4813-816d-ae809fba2510.png">

<img width="744" alt="Screenshot 2022-09-13 at 10 04 49 PM" src="https://user-images.githubusercontent.com/1686124/189958025-7b98106d-c5be-43aa-9168-4539e1f527ce.png">

[createpkgfail401.har.zip](https://github.com/LSFLK/MedicinesforLK/files/9559115/createpkgfail401.har.zip)

**Comment by akbandara** [comment]
Fixed with changes made to fix double submit issue.
