### ISSUE TITLE
Upload donor logo with aid package 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#479]
- [ ] Upload donor logo with aid package which is publicly visible in the donor portal/ public view. 

Rationale: to create more of a feeling that the platform is a coordinating platform for all organizations and not only red cross.

**Comment by akbandara** [comment]
Discussed during Scrum on 14 Sep and agreed to create 2 fields in the aid package record for URLs of image file:

ThumbnailImageURL = url to image file to be shown in aid package listings
BannerImageURL = url of image to be shown at top of aid package listing

**Comment by nshamit** [comment]
Manu will pick this up on the weekend.

**Comment by manuranga** [comment]
It shouldn't be mandatory, but you can't send `null`. Ie: ether filed is not there, or field is a string.

**Comment by dinuka-rp** [comment]
response when sending only thumbnail

```
data binding failed: {ballerina/lang.value}ConversionError, {"message":"'map<json>' value cannot be converted to 'admin_api:AidPackage': 
		field 'thumbnail' in record 'admin_api:AidPackage' should be of type 'string', found '()'
		field 'banner' in record 'admin_api:AidPackage' should be of type 'string', found '()'"}
```

**Comment by dinuka-rp** [comment]
> It shouldn't be mandatory, but you can't send null. Ie: ether filed is not there, or field is a string.

But, both banner & thumbnail are received as null and these are updated separately.

**Comment by manuranga** [comment]
Getting it back as null seems to be a ballerina bug, but was able to create aid pakage with or without thumbnail via postman.
![Uploading Screenshot 2022-09-23 at 1.55.07 AM.png…]()

**Comment by nshamit** [comment]
@dinuka-rp provide information to the user on the dimension of the image that needs to be uploaded as well. 

There is a use case where multiple donors will contribute to an aid package, so we will have to create a custom image with multiple logos in another application e.g. canva, and then upload the image with the correct dimensions.

**Comment by manuranga** [comment]
I reported this to Ballerina sql team, https://github.com/ballerina-platform/ballerina-standard-library/issues/3423
I will make it nullable as a workaround for now.
