### ISSUE TITLE
Make the Donate Now page UI mobile responsive

### ISSUE THREAD

**Issue by dinuka-rp** [LSFLK/MedicinesforLK#492]
**Is your feature request related to a problem? Please describe.**
The donor portal Donate Now page shows a messy UI with overflowing text.

**Describe the solution you'd like**
Make the text & surrounding elements mobile responsive.

**Describe alternatives you've considered**
Scale the text & adjust the containers/ package views based on the size of the content, without letting it overflow.

**Additional context**
![IMG_0498](https://user-images.githubusercontent.com/47103883/190648261-b3de3e93-6680-45bd-9dc2-dbb1866cc7db.PNG)
![IMG_0497](https://user-images.githubusercontent.com/47103883/190648281-86259ab4-eebc-4422-898c-c455f4fee6ec.PNG)

**Comment by dinuka-rp** [comment]
@kanushka Would u be able to look into this pls?

**Comment by kanushka** [comment]
I will check this

**Comment by dinuka-rp** [comment]
@kanushka pls check Slack, I sent you the env file. 
Take a pull as well, in case you haven't, and run _npm i_. There were quite a lot of changes in the sdk
