### ISSUE TITLE
Create a duplicate aid package API in Donor API

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#495]
During the review we identified that, below API can be accessed without an access token.

https://9d2b57ae-4349-44f2-971c-106ae09d244d-prod.e1-us-east-azure.choreoapis.dev/qmov/admin-api/1.0.0/aidpackages
https://9d2b57ae-4349-44f2-971c-106ae09d244d-prod.e1-us-east-azure.choreoapis.dev/qmov/admin-api/1.0.0/aidpackages/12

Screenshot 2022-09-18 at 13.28.55.png

This is a critical vulnerability .

This was left open intentionally. Ideally this has to be moved to the donor api (still as a public api) with but reduced information.

**Comment by nshamit** [comment]
@manuranga @dinuka-rp @anjula-sack can we close this?

**Comment by manuranga** [comment]
@SasinduDilshara will look into this.
