### ISSUE TITLE
Dev env: When deleting aid package, error message is shown, but deletion is allowed 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#496]
- [ ] When deleting aid package, error message is shown, but deletion is allowed. May need to change/ remove this error message. 

![Screen Shot 2022-09-19 at 17 28 20](https://user-images.githubusercontent.com/44461004/191013213-d32f4769-19fa-4a81-8307-88f4d2f61967.jpg)

Aid package is deleted as you can see in the screenshot below, so delete aid package functionality works fine. 
![Screen Shot 2022-09-19 at 17 28 37](https://user-images.githubusercontent.com/44461004/191013269-6a4eefef-d70c-4856-8954-86ffdec69112.jpg)

**Comment by udda1996** [comment]
@nshamit After the deletion, does the remaining quantities get updated as expected?

**Comment by nshamit** [comment]
@DilinaBandara @anjula-sack can you test this please?

**Comment by anjula-sack** [comment]
> @DilinaBandara @anjula-sack can you test this please?

I asked @DilinaBandara to test this.

**Comment by udda1996** [comment]
@DilinaBandara any update on testing?

**Comment by anjula-sack** [comment]
> @DilinaBandara any update on testing?

I"m testing this, seems like it's gone.

**Comment by anjula-sack** [comment]
I'll close this for now. Let's reopen this it's still there.
