### ISSUE TITLE
Dev env: When saving aid package, error message is received, but aid package is saved 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#497]
- [ ] Dev env: When saving aid package, error message is received, but aid package is saved 

https://user-images.githubusercontent.com/44461004/191015415-af51a01d-e0eb-4ae8-84b5-799fe8dd5b1f.MOV

Aid package has been successfully saved despite seeing the 'Something went wrong' error message on pressing 'Save draft'. 

![Screen Shot 2022-09-19 at 17 48 30](https://user-images.githubusercontent.com/44461004/191015493-2674dfbd-77d1-4dd4-ba80-1cb1be481577.jpg)

**Comment by dinuka-rp** [comment]
<img width="999" alt="image" src="https://user-images.githubusercontent.com/47103883/191022750-3fbde74d-6234-458e-88f9-ede42de3d769.png">
Backend is responding with status 500, with a SQL error

**Comment by nshamit** [comment]
@DilinaBandara @anjula-sack can we test this please?
