### ISSUE TITLE
Add tab to Admin portal to support upload of supplier information

### ISSUE THREAD

**Issue by akbandara** [LSFLK/MedicinesforLK#504]
**Is your feature request related to a problem? Please describe.**
It is not possible to add or update supplier information in the system

**Describe the solution you'd like**
The current tab labelled 'Suppliers' should be renamed to 'Quotations', and a new tab called 'Suppliers' created that allows upload of a CSV containing the details of suppliers. The behaviour of the upload functionality should be similar to the needs list handling - existing supplier details should be updated and any new suppliers in the CSV should be added to the SUPPLIER table in the DB.

**Describe alternatives you've considered**
An alternative would be a data entry form for viewing, adding / updating supplier details, but this would need more time to develop the UI elements.

**Comment by ayeshLK** [comment]
For supplier CSV we need following fields:
- Supplier Name
- Supplier Short Name
- Email
- Phone Number

@akbandara / @dinuka-rp FYI

**Comment by akbandara** [comment]
Here is an example CSV with supplier details
[Medical Needs - Suppliers.csv](https://github.com/LSFLK/MedicinesforLK/files/9739330/Medical.Needs.-.Suppliers.csv)

**Comment by dinuka-rp** [comment]
Waiting on Backend fix for API error
`12/10/2022 18:38:35 error: {ballerina}TypeCastError {"message":"incompatible types: 'string[]' cannot be cast to 'string[4]'"}`

**Comment by dinuka-rp** [comment]
@ayeshLK @manuranga were backend changes done to fix the TypeCastError?
Do I need to make any changes in the frontend code?

**Comment by manuranga** [comment]
Yes. No change needed from you.

**Comment by akbandara** [comment]
Have tested this fix in Dev and confirm it works.
