### ISSUE TITLE
CORS error when fetching aidpackge details in donor portal

### ISSUE THREAD

**Issue by dinuka-rp** [LSFLK/MedicinesforLK#506]
**Is your feature request related to a problem? Please describe.**
Backend: Getting aid package details in the donor portal seems to give a CORS error.
Frontend: The logo keeps spinning even after the request fails with 404. This needs to be fixed - stop showing the spinner & show an error message.

**Additional context**
<img width="760" alt="image" src="https://user-images.githubusercontent.com/47103883/191834317-fc00d522-848a-4e2c-9a76-39dff4ee42b1.png">

**Comment by dinuka-rp** [comment]
Please close this issue if it's redundant. I remember that this CORS error was there even before (not sure if it was this API). This is the first time that I experienced it.

**Comment by anjula-sack** [comment]
> Please close this issue if it's redundant. I remember that this CORS error was there even before (not sure if it was this API). This is the first time that I experienced it.

In the dev env. It is calling the `admin-api`.  We are using the `admin-api` to get the package details right?

**Comment by dinuka-rp** [comment]
@anjula-sack As I remember, we're using only donor apis now in the donor portal. Even in the above screenshot, it's using a donor API. This is in the local dev environment

**Comment by dinuka-rp** [comment]
@ayeshLK could you pleas look into this?
