### ISSUE TITLE
Comments need to be sorted with latest comments first 

### ISSUE THREAD

**Issue by jayasanka-sack** [LSFLK/MedicinesforLK#51]
**Is your feature request related to a problem? Please describe.**
Currently, the comments of an Aid Package or a Pledge are not properly sorted. 

**Describe the solution you'd like**
Comments need to be sorted with the latest comments first

**Comment by ManojLL** [comment]
can I work on this issue?

**Comment by jayasanka-sack** [comment]
Sure, go ahead!
