### ISSUE TITLE
When uploaded of supply quotation csv. Success message does not states the number of rows uploaded

### ISSUE THREAD

**Issue by DilinaBandara** [LSFLK/MedicinesforLK#510]
**Is your feature request related to a problem? Please describe.**
When uploading a CSV file a success message does not state the number of rows that are updated

**Describe the solution you'd like**
When we upload a CSV file to the Supplier Quotation Upload in Suppliers tab, the file is not uploaded successfully and there is no message which states the number of rows that are updated

**Additional context**
![image](https://user-images.githubusercontent.com/104125359/193800922-5758c790-3f61-4470-8bf9-eec2e2144a80.png)

**Comment by anjula-sack** [comment]
This issue is not there anymore.
