### ISSUE TITLE
Prod: After you enter a value as a pledge and the pledge is recorded, the value can still be seen in the box it was entered into

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#529]
- [ ] Prod: After you enter a value as a pledge and the pledge is recorded, the value can still be seen in the box it was entered into.

![Screen Shot 2022-10-13 at 21 05 59](https://user-images.githubusercontent.com/44461004/195641896-950b97fa-6495-498b-977c-58eb85a68a5a.jpg)

**Comment by dinuka-rp** [comment]
I thought that this was more of a feature. Even after refreshing the page, it'll show the amount pledged by the user in the input text field.

If the behavior needs to be changed, please assign me. I can work on a UI change to show the pledged amount by the user separately. @nshamit

**Comment by nshamit** [comment]
@dinuka-rp Isn't it unnecessary to do that when the pledge amount is recorded for a logged in donor to see in any case? See screenshot below.  Let's not have the amount pledged viewable in the input text field. 

![Screen Shot 2022-10-14 at 10 35 36](https://user-images.githubusercontent.com/44461004/195766665-e52d0dd3-d637-43f7-b70e-5712fbfcb9c5.jpg)

**Comment by dinuka-rp** [comment]
Currently, login isn't working in the local environment of the donor portal to test this.
