### ISSUE TITLE
Additions to the leadership team on About Us 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#535]
1. Sanjiva Weerawarana, PhD
Founder, Chairman & CEO of WSO2

2. Dr. Natasha Perera
Medical Coordinator to Red Cross Elixir Project

**Comment by nshamit** [comment]
@anjula-sack please remove Charuka Karunanayake also

**Comment by anjula-sack** [comment]
> @anjula-sack please remove Charuka Karunanayake also @dinuka-rp

sure
