### ISSUE TITLE
Donor portal not showing aid package update posts when user not logged in

### ISSUE THREAD

**Issue by akbandara** [LSFLK/MedicinesforLK#541]
**Is your feature request related to a problem? Please describe.**
When viewing the detail of an aid package in the donor portal, the update messages associated with the aid package is not shown unless the user is logged in.  Below are screen shots of the same aid package for anonymous and logged in users

**Anonymous user view**
<img width="80%" alt="Screenshot 2022-10-15 at 21 48 35" src="https://user-images.githubusercontent.com/3705261/196007056-1015cd00-bde3-4271-a504-67ac2b048fd4.png">

**Logged in user view**
<img width="80%" alt="Screenshot 2022-10-15 at 21 52 58" src="https://user-images.githubusercontent.com/3705261/196007145-f2a4627e-8e3e-4a57-8e18-1448f40af719.png">

**Describe the solution you'd like**
The updates should be shown for all users

**Comment by anjula-sack** [comment]
@akbandara This is due to `aidpackages/${packageID}/updatecomments` API is not being public. We need to make this API public @manuranga

**Comment by manuranga** [comment]
made public
