### ISSUE TITLE
Website / Donor Portal About Us: partners section, please add Eclektik Designs logo and text 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#550]
- [ ] Website / Donor Portal About Us: partners section, please add Eclektik Designs logo and text 

![Eclektik Designs](https://user-images.githubusercontent.com/44461004/196046976-04ed6a31-5a03-4b84-a627-27582081952f.jpeg)

Creation of the project overview video

**Comment by nshamit** [comment]
Also add Dr. Laura Leets to the Volunteer section please

**Comment by RandilaP** [comment]
May I work on this @nshamit

**Comment by nshamit** [comment]
@anjula-sack says please go ahead. @RandilaP please complete this today (Monday 17th Oct)

**Comment by RandilaP** [comment]
@nshamit Where can I find the text and the details about Dr.Laura Leets.

**Comment by nshamit** [comment]
@RandilaP you don't need any, Randila, just list her as a volunteer in the volunteer section of the About Us page.

**Comment by RandilaP** [comment]
@nshamit okay. And what about the text of Eclektic Designs

**Comment by RandilaP** [comment]
@nshamit Don't they have a link?

**Comment by nshamit** [comment]
I searched for it last evening, Randila, when I was creating the issue. They didn't have anything I could use. Shall we just quickly finish this off ?

**Comment by RandilaP** [comment]
okay

**Comment by nshamit** [comment]
@RandilaP @anjula-sack 
Text for Eclektic designs: 

Eclektik Designs is a US based start-up that provides a full suite of design solutions that include online video marketing materials, trade-show graphics, logo designs and professional brochures.
