### ISSUE TITLE
Dev: Donor portal, a donor can only pledge a max of two times before you are prevented from pledging. 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#551]
Dev: Donor portal, a donor can only pledge a max of two times before you are prevented from pledging. 

To replicate:
1. Select aid package in Goal pending status
2. Pledge an amount towards the total 
3. Pledge again (revise the pledge)
4. Now you are prevented from pledging again. 

![Screen Shot 2022-10-16 at 23 25 52](https://user-images.githubusercontent.com/44461004/196050556-3e730ca2-5919-4492-9206-9d0a4dc1c8a6.jpg)

**Comment by dinuka-rp** [comment]
I can't figure out how this 0 is showing up :(
@anjula-sack can u please take a look at this?
