### ISSUE TITLE
Prod: Update message on aid package shows some script (Essential Medicines Nov 22 Aid Package)

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#564]
Prod: Update message on aid package shows some script (Essential Medicines Nov 22 Aid Package):

Script: <script>alert(0)</script> 
shows in the update messages 

![Screen Shot 2022-10-21 at 18 08 03](https://user-images.githubusercontent.com/44461004/197197894-311337be-9d3c-420b-ae64-cd5652c7b0e7.jpg)
![Screen Shot 2022-10-21 at 18 07 47](https://user-images.githubusercontent.com/44461004/197197917-fc7cf129-9e27-4883-a0ee-3b7d0aa9d776.jpg)

**Comment by anjula-sack** [comment]
Can't we delete that comment from the admin? @nshamit

**Comment by anjula-sack** [comment]
@manuranga says that this could be coming from testing. @nshamit can you delete this from the admin UI?

**Comment by dinuka-rp** [comment]
I think it would probably be better to start showing who posted the comments since that would increase accountability.

@nshamit @anjula-sack @manuranga what do you all think?

**Comment by dinuka-rp** [comment]
I agree that it could be coming from testing too.

**Comment by nshamit** [comment]
@anjula-sack hi i did not see this in prod anymore. Can we close this?

**Comment by anjula-sack** [comment]
> @anjula-sack hi i did not see this in prod anymore. Can we close this?

yes
