### ISSUE TITLE
Create direct route for individual donors (public) to donate 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#571]
1. Create a button from the Donate page banner directly to give.asia site.  Banner needs a sentence explaining connection to aid packages:  “We are currently accepting donations to a general fund that will support multiple aid packages.” with ‘Donate’ button.

2. Default tab to go to when you click on the Donate tab is ‘goal pending’ if there are packages to show here. If not, Goal Reached.  Currently the default is to go to goal reached.

**Comment by akbandara** [comment]
here is a mock up of what the ‘Donate’ banner could look like on the aid package page.  I am also attaching the thumbnail image to go with the banner.
<img width="731" alt="Screenshot 2022-10-31 at 19 47 19" src="https://user-images.githubusercontent.com/3705261/199098534-aba20ecb-1dcd-4692-be55-2b175a5c290a.png">

<img width="240" alt="elixir-slrcs-banner" src="https://user-images.githubusercontent.com/3705261/199098554-34639295-7494-42c3-95a0-622b81a43a70.png">
