### ISSUE TITLE
Change the image displayed with the shared link to the thumbnail image of the aid package

### ISSUE THREAD

**Issue by dinuka-rp** [LSFLK/MedicinesforLK#576]
**Is your feature request related to a problem? Please describe.**
Change the image displayed with the shared link to the thumbnail image of the aid package. (Suggestion by @akbandara)

**Describe the solution you'd like**
Use React Helmet to change the meta tag to use the aidpackage thumbnail as the img.
https://www.digitalocean.com/community/tutorials/react-react-helmet
https://ogp.me/

_This might not work for Client rendered React. Might have to use a Server-side framework like Next.JS to get it to load images from remote locations (currently package images are loaded from file-sharing links such as dropbox)._

**Comment by dinuka-rp** [comment]
@nipunsampath were you able to try this out?

**Comment by dinuka-rp** [comment]
https://stackoverflow.com/questions/19778620/provide-an-image-for-whatsapp-link-sharing

**Comment by dinuka-rp** [comment]
https://www.kapwing.com/blog/how-to-add-dynamic-meta-tags-server-side-with-create-react-app/
https://github.com/facebook/create-react-app/issues/1261

**Comment by akbandara** [comment]
This 'Sharing Debugger' from the Meta Developer site could also help us figure out what's going on: https://developers.facebook.com/tools/debug/

**Comment by nipunsampath** [comment]
Closing this since we will not be using something like NextJS for supporting this kind of requirement.
