### ISSUE TITLE
Request from Red Cross SL : Change status ticks to check boxes with spacing 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#583]
The Red Cross mentioned that the status line and ticks were not clear enough, and were confusing to them. 

![Screenshot 2022-12-26 at 11 06 28](https://user-images.githubusercontent.com/44461004/209507340-4bcb096c-f40b-4627-a798-5dd5d1cca13e.jpg)

They would prefer the following:

- [ ] Check boxes which clearly show what the current status is
- [ ] Greyed out statuses that have been achieved

**Comment by Tharindu37** [comment]
I would like to work on this

**Comment by anjula-sack** [comment]
> I would like to work on this

Go ahead @Tharindu37

**Comment by Tharindu37** [comment]
![Screenshot_20221230_080431](https://user-images.githubusercontent.com/88996660/210028865-2edaf4f7-7913-4e29-9326-c9f3b59d5b48.png)

@anjula-sack @nshamit How about this?

**Comment by anjula-sack** [comment]
> 

I think this looks good.
