### ISSUE TITLE
Add post to newsroom about the Microsoft donation through Elixir

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#585]
Can we update the below Facebook article on the website please? 

Date: January 9th, 2023
Title: Microsoft donates medicines worth USD 20,000 through Elixir system, to help overcome the current medicine shortage in Sri Lanka. 

Link: https://www.facebook.com/133902706641597/posts/pfbid02puSRKL5kprdmM23t5gPqwN2jRDyGCqvU7LMRGJUeS99RqAwqtWJnzat6PyBciqnl/?sfnsn=mo

**Comment by nshamit** [comment]
![94569a22-4cf3-47ef-885b-3fe7d43317d2](https://user-images.githubusercontent.com/44461004/212070144-08402a48-bc58-4b97-a65b-6e8dbdfa08f5.jpg)

**Comment by Tharindu37** [comment]
I would like to work on this

**Comment by anjula-sack** [comment]
> I would like to work on this

Go ahead @Tharindu37
