### ISSUE TITLE
Change package status to check boxes in donor portal

### ISSUE THREAD

**Issue by anjula-sack** [LSFLK/MedicinesforLK#586]
**Is your feature request related to a problem? Please describe.**
The Red Cross mentioned that the status line and ticks were not clear enough, and were confusing to them. 

![Screenshot 2022-12-26 at 11 06 28](https://user-images.githubusercontent.com/44461004/209507340-4bcb096c-f40b-4627-a798-5dd5d1cca13e.jpg)

**Describe the solution you'd like**
- Make it look like in the admin portal

![image](https://user-images.githubusercontent.com/43912578/211821853-2729e797-7500-4ac1-afc7-f88f92be1c9f.png)

**Comment by Tharindu37** [comment]
@anjula-sack Sure
