### ISSUE TITLE
Update Newsroom of website with the Kandy Donation Face Book Post. 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#588]
Please find attached Kandy Donation Face Book post link and the picture. Please share it in Elixir Website Page.

Date: Jan 11th, 2023
Title: Vital surgical supplies valued at over 2 million rupees handed over to the Kandy National Hospital through the Sri Lanka Red Cross Society. 

https://www.facebook.com/133902706641597/posts/pfbid0Cw9T4BJgc63CvAnieRpNF99GhKdJASpsT9xQKPBJtqPXsTQFoBfntRmd3GHBARhfl/?mibextid=Nif5oz

**Comment by nshamit** [comment]
![WhatsApp Image 2022-12-16 at 09 20 32](https://user-images.githubusercontent.com/44461004/212000914-8e239c60-a48e-4009-9e9c-d94310c45a67.jpeg)

**Comment by Tharindu37** [comment]
I would like to work on this

**Comment by anjula-sack** [comment]
> I would like to work on this

Go ahead @Tharindu37
