### ISSUE TITLE
Update the needs list as of Jan 17, 2023

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#593]
[Essential List New Update Edited Final as at 11.01.2023.xlsx](https://github.com/LSFLK/MedicinesforLK/files/10433533/Essential.List.New.Update.Edited.Final.as.at.11.01.2023.xlsx)

Date to select : Jan 17, 2023.

**Comment by akbandara** [comment]
Needs list is now updated - a few items couldn't be found on the existing NMRA list, but have added them on the assumption that these are newly approved items.
