### ISSUE TITLE
Update the newsroom with the Singapore Red Cross Donation FB Post Link

### ISSUE THREAD

**Issue by anjula-sack** [LSFLK/MedicinesforLK#594]
**Is your feature request related to a problem? Please describe.**
- We need to update the newsroom with the Singapore Red Cross Donation FB Post Link

**Describe the solution you'd like**
- Date: January 24, 2023  
- Title: The Singapore Red Cross recently donated medicine and medical equipment to the Ministry of Health valued at over USD 85,000 towards resolving the ongoing crisis. 
- Link: https://www.facebook.com/133902706641597/posts/pfbid02vuZFpZdr6BVaGFtRTTfkWE3NnZKxcp3NtzLG9JKy1UhWvY2AxCTa2ZqYFzzxZ6mHl/?mibextid=Nif5oz
![Donation pic](https://user-images.githubusercontent.com/43912578/215364219-3851714a-582f-4d74-bbdd-988c0b803b69.JPG)

**Comment by anjula-sack** [comment]
@Tharindu37 would you like to work on this?

**Comment by Tharindu37** [comment]
@anjula-sack Sure
