### ISSUE TITLE
Update to Newsroom: Uber Sri Lanka Donation Facebook post 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#598]
https://www.facebook.com/133902706641597/posts/pfbid02kM7Ti4Q3i4Kq4hrrfxdagcJsR5v81zNVZ2uNiNuf8wU88sWTJi2kUG51FwP14MNZl/?sfnsn=mo

Date : 2nd February 2023
Title : Uber Sri Lanka donates medicines to the Ministry of Health Sri Lanka valued at over USD $15,000 (LKR 5,000,000) through Elixir
Picture: Please obtain the photo from Facebook post.

**Comment by Tharindu37** [comment]
I would like to work on this

**Comment by anjula-sack** [comment]
> I would like to work on this

Go ahead! @Tharindu37
