### ISSUE TITLE
Update the newsroom with the Map International Donation FB Post Link

### ISSUE THREAD

**Issue by anjula-sack** [LSFLK/MedicinesforLK#601]
**Is your feature request related to a problem? Please describe.**
- We need to update the newsroom with the Map International Donation FB Post Link

**Describe the solution you'd like**
- Date: 2nd February 2023
- Title: Sri Lanka Red Cross Society's medical donation matching platform, 'Elixir,' facilitated a donation of medicines and medical equipment worth more than USD 512,000.00 by MAP International and Sevalanka Foundation, aiming to support the health sector's ongoing crisis
- Link: https://www.facebook.com/133902706641597/posts/pfbid02fG8wvq4HNr8DoH4K2s3DE1SYSuJ1NGiWak6WNMibEr5zzcHHARm2W4uFRMCgdNwfl/?mibextid=Nif5oz
![image](https://user-images.githubusercontent.com/43912578/218256317-e4c01d7e-efe8-405e-9441-42e7c7cf3dae.png)

**Comment by Tharindu37** [comment]
I would like to work on this
