### ISSUE TITLE
Add LinkedIn icon and link to Elixir website 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#604]
Please add the LinkedIn icon to the Elixir website (https://elixir.redcross.lk/), and link it to the following page: https://www.linkedin.com/company/sri-lanka-red-cross-societysl/

**Comment by Tharindu37** [comment]
I would like to work on this

**Comment by anjula-sack** [comment]
> I would like to work on this

Sorry @Tharindu37, @ruhaim has sent a PR already.
