### ISSUE TITLE
Add introduction to Elixir video in the Newsroom page 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#606]
Please include this Elixir introduction video in the Newsroom section of the https://elixir.redcross.lk/ website:

https://user-images.githubusercontent.com/44461004/219546506-2b9fb3cb-0716-46c8-be95-c4cc2cea6a5f.MP4

Position: above the news section. It should be one of the first things they see before they need to scroll down to the news articles. 

Sharing: We want anyone to be able to share a link to the video in social media text, on social media posts/stories etc.

**Comment by Tharindu37** [comment]
I would like to work on this

**Comment by anjula-sack** [comment]
> I would like to work on this

Go Ahead @Tharindu37

**Comment by Tharindu37** [comment]
![Screenshot 2023-02-18 083725](https://user-images.githubusercontent.com/88996660/219828658-960b67c7-e88c-4d9f-9574-9e6d184ea4d8.jpg)

@anjula-sack what do you think about this one?

**Comment by anjula-sack** [comment]
> ![Screenshot 2023-02-18 083725](https://user-images.githubusercontent.com/88996660/219828658-960b67c7-e88c-4d9f-9574-9e6d184ea4d8.jpg)
> 
> @anjula-sack what do you think about this one?

Can you send the draft PR? @Tharindu37 Then we can decide.

**Comment by Tharindu37** [comment]
@anjula-sack  Ok
