### ISSUE TITLE
Add Elixir Introduction Video into Elixir Homepage of the website 

### ISSUE THREAD

**Issue by fedrosuren** [LSFLK/MedicinesforLK#612]
Please add the Elixir Introduction Video in Elixir home page. Please find the video attached. 
Please insert video next to area which says "Coordinated donations for Sri Lanka’s medical supply needs"

![SC Elixir](https://user-images.githubusercontent.com/126852804/222693562-e7b32fd4-9bf3-4ef5-b251-722a4b9cf86e.png)

**Comment by Tharindu37** [comment]
@anjula-sack I would like to work on this
