### ISSUE TITLE
Decrease the margin of the intro video in the mobile view

### ISSUE THREAD

**Issue by anjula-sack** [LSFLK/MedicinesforLK#616]
**Is your feature request related to a problem? Please describe.**
-  The bottom margin is too big for mobile view. We need to remove it.

How it looks like now,

<img width="426" alt="image" src="https://user-images.githubusercontent.com/43912578/223943153-d843c1ae-8d49-45e0-81de-ed634b4388e8.png">

How it should look like,

<img width="424" alt="image" src="https://user-images.githubusercontent.com/43912578/223943538-5d1ea464-3c7f-42aa-9cdd-9f61c76d418d.png">

**Describe the solution you'd like**
- Try removing the min-height of the video

**Comment by Sanjana0319** [comment]
I would like to work on this.
