### ISSUE TITLE
Update the year in the footer

### ISSUE THREAD

**Issue by anjula-sack** [LSFLK/MedicinesforLK#619]
**Is your feature request related to a problem? Please describe.**
- The year in the footer is outdated. It needs to be updated.

<img width="308" alt="image" src="https://user-images.githubusercontent.com/43912578/224353492-bebb8847-146f-4415-b7ca-3885b3d11ea3.png">

**Describe the solution you'd like**
- Use a dynamic year in the footer instead of the hardcoded year
- Refer to this

https://www.w3schools.com/jsref/jsref_getfullyear.asp

**Comment by Sanjana0319** [comment]
I would like to work on this.
