### ISSUE TITLE
Remove unwanted files from the project

### ISSUE THREAD

**Issue by anjula-sack** [LSFLK/MedicinesforLK#622]
**Is your feature request related to a problem? Please describe.**
There are some unwanted files in the project that needs to be removed

**Describe the solution you'd like**
Remove the following files,
package-lock.json https://github.com/LSFLK/MedicinesforLK/blob/development/package-lock.json
.DS_Store https://github.com/LSFLK/MedicinesforLK/blob/development/.DS_Store

**Comment by Sanjana0319** [comment]
I will correct this mistake.
