### ISSUE TITLE
Update the newsroom with the International Federation of Red Cross Donation

### ISSUE THREAD

**Issue by anjula-sack** [LSFLK/MedicinesforLK#628]
**Is your feature request related to a problem? Please describe.**
- We need to update the newsroom with the International Federation of Red Cross Donation FB Post Link

**Describe the solution you'd like**
- Date: 22nd March 2023
- Title: [International Federation of Red Cross and Red Crescent Societies](https://www.facebook.com/IFRC/?__cft__[0]=AZWfqvZI598_7BNaDUWaaRupgGAXH0X0zIDbc5_ffhwVFCazl-p9yUEyzO5u711jHXDDLQgpASrpHZGZOcP76YyQLhbqAp_EIOL_1OgQj_4tgRXXLMvf0PRB-agsEx4YGh72JKSyCSzlbhlHToLwhOwW&__tn__=kK-R)(IFRC) donated USD 41,531.88 on March 22, 2023 via ‘Elixir’, Sri Lanka’s first medical donation matching platform by the [Sri Lanka Red Cross Society](https://www.facebook.com/srilankaredcross/?__cft__[0]=AZWfqvZI598_7BNaDUWaaRupgGAXH0X0zIDbc5_ffhwVFCazl-p9yUEyzO5u711jHXDDLQgpASrpHZGZOcP76YyQLhbqAp_EIOL_1OgQj_4tgRXXLMvf0PRB-agsEx4YGh72JKSyCSzlbhlHToLwhOwW&__tn__=kK-R).

- Link:  https://web.facebook.com/133902706641597/posts/pfbid0BEgnW331SxozgLPedBqsAXFovowZiqKP5ywx86xVwoYmAsee3XnBg71eJesjN2ZTl/?mibextid=Nif5oz&_rdc=1&_rdr

![Donation Image](https://user-images.githubusercontent.com/43912578/230539597-72756336-d9c3-4a27-a28a-461a7a9e6da9.jpeg)

**Comment by Sanjana0319** [comment]
I would like to work on this.
