### ISSUE TITLE
Add Kandy hospital Donation testimonial into Elixir Home Page #631

### ISSUE THREAD

**Issue by fedrosuren** [LSFLK/MedicinesforLK#631]
Please add the Kandy hospital Donation testimonial Elixir home page Please find the testimonial attached.
Please insert testimonial between the Health Ministry logo section, and the Donor logos.

“We are grateful to the Sri Lanka Red Cross Society for donating Sevoflurane to our hospital; with their assistance, we were able to treat patients in all operating rooms for more than three months. Because of the ongoing crisis, operations were temporarily halted, causing issues with our service to our patients. SLRCS's contribution made things easier and allowed almost all of the hospital's operating rooms to continue. The donated medication is a critical medication that must be available in hospitals. The donation totaled two million rupees, and we used it to treat over 100 patients. We are extremely grateful for the assistance provided," said the Ward Master of the National Hospital in Kandy, Sri Ranganayake Bandara.

**Comment by Sanjana0319** [comment]
I would like to work on this
