### ISSUE TITLE
Update  ‘Donate’ button on Elixir to go straight to Give Asia site

### ISSUE THREAD

**Issue by fedrosuren** [LSFLK/MedicinesforLK#638]
Please update the "Donate now" button to direct donors straight to the Give Asia website. It is located on the left side of the Elixir Home page with the Elixir introduction video. 

Give Asia link has been attached

![image](https://user-images.githubusercontent.com/126852804/235900363-8bc4aa84-2da1-4416-8ec8-f45211e9b799.png)

Give Asia Link : https://give.asia/campaign/medicince-for-sri-lanka-poject-elixir/donate?#/amount 

![image](https://user-images.githubusercontent.com/126852804/235900708-9ef00085-aa42-4e76-8e1e-0f09f82f7061.png)

**Comment by Sanjana0319** [comment]
I would like to work on this

**Comment by anjula-sack** [comment]
> I would like to work on this

Go ahead @Sanjana0319
