### ISSUE TITLE
Donor Portal Issues 

### ISSUE THREAD

**Issue by samisa-abeysinghe** [LSFLK/MedicinesforLK#64]
Test round on donor portal done on 8th July 9.00 am 
I found the following listed issues 

- [x] Clicking on the logo does not take you to the home page 
- [x]  Clicking on donate button does nothing – probably not wired yet (on the Request Medicine page) 
- [x] Register on the login page does not work 
- [x] #94
- [x] #92
- [x] #95
- [x] FB, insta and twitter icons on the footer are not linked 
- [x] Privacy, terms and cookies links on the footer are not linked to proper content 
- [x] A copyright statement is missing on the site footer 
- [ ] https://github.com/LSFLK/MedicinesforLK/issues/91

**Comment by nshamit** [comment]
I'll get answers to these bullets:

- [ ] news-room page media contacts section has some dummy numbers
- [ ] news-room page needs to be filled with some meaningful content – do we have access to such?
- [ ] FB, insta and twitter icons on the footer are not linked
- [ ] Privacy, terms and cookies links on the footer are not linked to proper content
- [ ] A copyright statement is missing on the site footer

**Comment by nshamit** [comment]
- [ ] Clicking on donate button on home page does not take you to the aid package -specific details page
- [ ] aid package details page must be connected to the donate now page

**Comment by nshamit** [comment]
Remaining issues have been created as separate issues.
