### ISSUE TITLE
Admin Portal Issues

### ISSUE THREAD

**Issue by samisa-abeysinghe** [LSFLK/MedicinesforLK#65]
Test round on donor portal done on 8th July 9.30 am
I found the following listed issues

- [x] On home page, aid packages take a while to load and there is a brief screen with “No Data Found” on the screen 
- [x] Improve the error message such as “loading …” initializing …”etc. 
- [x] Look into loading time – why does it take seconds to load? 
- [x] Home page search does not work for aid package filtering 
- [x] Do we have pagination on home page for Aid Packages list? 
- [x] On Aid Packages page, Next and Back buttons are not consistent in color and position, is that by design? 
- [x] Can we have some data filled on second step, manage aid packages to see how it look and feel? 
- [x] Analytics menu item is not linked/wired 
- [x] Footer has @OpenSource.com. Can we please replace with proper text. Also, I think we need to have a copyright in there. 
- [x] Login is not wired 
- [x] Help is not wired 

Have we done a proofing of the backend performance? Some of the pages feels slow to load once clicked.

**Comment by nshamit** [comment]
Separate issues have been created for 

- [ ] loading
- [ ] help, analytics not being wired
- [ ] login
- [ ] loading issue. 

Rest of the issues are closed.
