### ISSUE TITLE
Please add Company Logo Description into Partners section 

### ISSUE THREAD

**Issue by fedrosuren** [LSFLK/MedicinesforLK#651]
Add the Flipit Media (Pvt) Ltd logo and company information to the Elixir website's "About us" column's "Partners" section. 

![image](https://github.com/LSFLK/MedicinesforLK/assets/126852804/a2df7da0-0c7a-4dd0-9f76-5e56a04c3585)
![image](https://github.com/LSFLK/MedicinesforLK/assets/126852804/961ed06f-2fe0-4f25-b574-a9c1f84f31c2)

Please find attached Company Description and the Logo 

Flipit Media is a creative content creation agency specializing in Cinematography, Photography, Advertising Collateral, Social Media Marketing, 2D/3D Animation, and Architectural visualization. Our services also include Content Strategy & Creation, Strategizing & Consultancy Services for Advertising on Mass Media and Digital platforms.

![Flipit-New-Logo](https://github.com/LSFLK/MedicinesforLK/assets/126852804/6030f7a8-78cb-4cbc-b833-b7490376bb7e)

**Comment by Sanjana0319** [comment]
I would like to work on this.

**Comment by Sanjana0319** [comment]
Change the Flipit div order.
