### ISSUE TITLE
Please add Company Logo Elixir Website Current Donor section

### ISSUE THREAD

**Issue by fedrosuren** [LSFLK/MedicinesforLK#657]
Add the Map International logo to the Elixir website's "Home" column's "Current Donors" section.

![image](https://github.com/LSFLK/MedicinesforLK/assets/126852804/5fa0d375-85a4-4486-a4f1-7e4482be9d54)
![image](https://github.com/LSFLK/MedicinesforLK/assets/126852804/8a30219f-5c9f-48fd-8900-e7d7f6494bce)

Please find attached Map International Company Logo

![New MAP Logo 2022 rgb](https://github.com/LSFLK/MedicinesforLK/assets/126852804/013b99c8-d5d3-4323-9f74-ebb9ba3cd2aa)
 Logo

**Comment by Sanjana0319** [comment]
I would like to work on this.
