### ISSUE TITLE
Please add Company Logo Elixir Website Current Donor section

### ISSUE THREAD

**Issue by fedrosuren** [LSFLK/MedicinesforLK#660]
Add the Seva Lanka Foundation logo to the Elixir website's "Home" column's "Current Donors" section.

![image](https://github.com/LSFLK/MedicinesforLK/assets/126852804/ee26b304-386e-4d43-accf-41260a9b2fd2)

Please find attached Seva Lanka Foundation Company Logo

![ca6c6b1a-7a22-4058-a6fc-94fd7beb0c8c](https://github.com/LSFLK/MedicinesforLK/assets/126852804/d06f4d7a-0221-462f-afca-a6bed7da10d0)

**Comment by Sanjana0319** [comment]
I would like to work on this.
