### ISSUE TITLE
Add copyright statement to the footer

### ISSUE THREAD

**Issue by jayasanka-sack** [LSFLK/MedicinesforLK#69]
Add the following copyright statement to the footer:
Copyright © www.elixir.redcross.lk | All rights reserved

Probably on the following area.
<img width="1299" alt="Screenshot 2022-07-08 at 14 17 56" src="https://user-images.githubusercontent.com/33048395/177954804-5b3b1be9-b5b3-4fac-bd32-f260732c206c.png">

**Comment by RandilaP** [comment]
can i work on this
