### ISSUE TITLE
Link social media icons in the footer

### ISSUE THREAD

**Issue by jayasanka-sack** [LSFLK/MedicinesforLK#70]
Link the following:

- Facebook: https://www.facebook.com/pages/Sri-Lanka-Red-Cross-Society/133902706641597
- Twitter : https://twitter.com/#!/SLRedCross
- YouTube : https://www.youtube.com/user/srilankanredcross
- Instagram : https://instagram.com/slredcross?igshid=YmMyMTA2M2Y=

**Comment by RandilaP** [comment]
can i work on this

**Comment by jayasanka-sack** [comment]
Sure. Go ahead
