### ISSUE TITLE
Change Email address on the donors page

### ISSUE THREAD

**Issue by jayasanka-sack** [LSFLK/MedicinesforLK#90]
**Is your feature request related to a problem? Please describe.**
There's a typo in the email. The correct one should be [inquiries@redcross.lk](mailto:inquiries@redcross.lk)

https://donor-portal-medicinesfor-lk.vercel.app/donors

**Comment by RandilaP** [comment]
Can I work on this

**Comment by YaiyaSam** [comment]
> Can I work on this
Sure, go ahead!
