### ISSUE TITLE
Update dummy numbers on the News Room page

### ISSUE THREAD

**Issue by jayasanka-sack** [LSFLK/MedicinesforLK#92]

**Comment by nshamit** [comment]
Please include these details:

1. Mr. Naveendra SENARATHNE
Media Focal Point
+94 (71) 433 3331 
naveendra.senarathna@redcross.lk

2. Sri Lanka Red Cross Society
National Headquarters
106, Dharmapala Mawatha,
Colombo 07, Sri Lanka
[T] (94) 11 2691095 , (94) 11 2691095
[F] (94) 11 2682675
[E] info@redcross.lk

**Comment by jayasanka-sack** [comment]
Thanks @nshamit !

**Comment by jayasanka-sack** [comment]
@RandilaP Could you please work on this?

**Comment by RandilaP** [comment]
sure @jayasanka-sack

**Comment by nshamit** [comment]
Hi Team, please add the following to the newsroom contacts: 

Zafran Packeerally – 070 378 8685 email: zafran.packeerally@redcross.lk
