### ISSUE TITLE
Change copyright for website (once again)

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#93]
@jayasanka-sack @YaiyaSam @Gravewalker666 @RandilaP 

Change to: 
Copyright © elixir.redcross.lk  All rights reserved.

**Comment by jayasanka-sack** [comment]
Shouldn't it be elixir.redcross.lk?

**Comment by nshamit** [comment]
Change to:
Copyright © elixir.redcross.lk All rights reserved.

**Comment by ManojLL** [comment]
Shall I work on this?

**Comment by nshamit** [comment]
Yes, please do.

**Comment by jayasanka-sack** [comment]
@ManojLL Please update the admin portal footer as well.
