### ISSUE TITLE
News room page needs to be filled with some meaningful content 

### ISSUE THREAD

**Issue by jayasanka-sack** [LSFLK/MedicinesforLK#95]

**Comment by nshamit** [comment]
[Press releases]

- [ ] Microsoft's fundraising efforts, and contribution of Azure resources. Microsoft onboarding of PR resource on 12th July. Aim for press release by 15th. Already passed on Dr. Mahesh's contact for an interview. 
- [ ] Helani, Ashok, Red Cross + The Last Word + LSF partnership on platform with now about 30+ volunteers. 
- [ ] Global Red Cross offices raise funds for Sri Lanka e.g. Singapore Red Cross 
- [ ] ICRC pledges their support to Sri Lanka Red Cross, efforts on the ground in Sri Lanka
- [ ] Red Cross signs agreement with MOH, SLMA on this project to resolve the medicines crisis. Fundraising and support of Red Cross work.

**Comment by jayasanka-sack** [comment]
Ignore the previous comment.

The following items should be there:
**Also, Have the date before the title.**

July 29th 2022: The[ International Committee of the Red Cross](https://www.facebook.com/ICRC/?__cft__[0]=AZW4cggwp3pZgw5hRmdDSrkACb2ulZq2_4cK7kxUBRNZGs3SyXgW_UkcFhC9JKmNsq55HvbrP89OHaOmI8ShqHnx4PP17kGZAmPUIHEw47ejRObeIn5TptJUySj7swRCygPMvkGo0ykGjHSujDUc4i8K0m7EIwI3pko1gDicqGl27A2IpYPAeP-NHxuOCXVwWf0&__tn__=kK-R) has donated a consignment of 10,000 blood bags to the National Blood Bank.

https://www.facebook.com/srilankaredcross/posts/pfbid0cC25DMKmdghvTXLhJBQxscS3buPkLuB3Fu5PLCPBDmmnuEQEZGoXFRdRDBfKuvnjl 

—-----------

June 9th 2022: Understanding the critical requirement of blood in Sri Lanka,[ Sri Lanka Red Cross Society - Colombo Branch](https://www.facebook.com/ColomboBranchSLRCS/?__cft__[0]=AZVdzESiNZmMDppjDFDFrtDKYP5TPvXUVg5UOGU7I4kFic6nAR27fnlOnNAEem0zd4wQROEZFXBGAiw_ybObt19bCxnEv41xO7XcCmcomUa6dHyx9JjWJVPY2p_dKlGpz8dzclKzaHdlNo8Vza-L3HLIypBZO_nHoDde_PObTB1z1cOIYWG6ujiHv5umu2CPvO8&__tn__=kK-R) organised a blood donation camp in Colombo, today. 

https://www.facebook.com/srilankaredcross/posts/pfbid02Lgtf7Zh6wLDjfgyBA53hPWxMDYKjR5TnbtDNY4RZD8sw6Rnd1Wj9HPfgCcfCzLTCl 

—-----------

May 31st 2022: In a time of grave crisis where essential medicines are scarce or not available at all, the Singapore Red Cross has donated medicines worth around 68,500 SGD. 

https://www.facebook.com/srilankaredcross/posts/pfbid0EdnJsD7qfC7Bc432CoTUtT2oBVM926G44gnTEqTfzJvGRGwRujtpajQivWpU6tHDl

**Comment by nshamit** [comment]
Hey @jayasanka-sack I have the historical data. I can create aid packages from that. Thanks for the links/details, I'll use them to double check.
