### ISSUE TITLE
Create demo script for the Demo session 1

### ISSUE THREAD

**Issue by jayasanka-sack** [LSFLK/MedicinesforLK#97]
**Is your feature request related to a problem? Please describe.**
Create a demo script for Demo session 1 that is planned to happen on the 10th or 11th. 

Here's the list of things that we are planning to fix. (still working on creating issues)
https://github.com/LSFLK/MedicinesforLK/milestone/2

**Comment by nshamit** [comment]
Refer demo script here: https://docs.google.com/document/d/1Tve4HAdDCX6ONqspX2UGPTsEGcQ1-4zq9JkEwDOThXI/edit#
